### ISSUE TITLE
third person disapperead (xml float values output wrong because of varying international culture)

### ISSUE THREAD

**Issue by legendzwolf** [Monitor144hz/Pandora-Behaviour-Engine-Plus#10]
cant see in third person after pandora just all  tdm patches enabled

**Comment by legendzwolf** [comment]
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2023 11 12 - 17 21 20 94](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/68744110/55da3e55-13e9-4e9c-b817-abae3e5011d5)

**Comment by Monitor144hz** [comment]
Engine.log please

**Comment by legendzwolf** [comment]
[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13328562/Engine.log)

**Comment by Monitor144hz** [comment]
doesn't seem to be anything weird. Does this problem go away when you use Nemesis?

**Comment by legendzwolf** [comment]
yes

**Comment by Monitor144hz** [comment]
What version are you using?

**Comment by legendzwolf** [comment]
0.41 but 0.4 had the same problem for me

**Comment by Monitor144hz** [comment]
try disabling the xpmse patch please

**Comment by Monitor144hz** [comment]
did you try it without any patch active? Cannot reproduce this on my end

**Comment by Monitor144hz** [comment]
I suggest testing the mods one by one because the number of patches is fairly small

**Comment by legendzwolf** [comment]
do i need pandora base?

**Comment by Monitor144hz** [comment]
you can disable it just in case

**Comment by legendzwolf** [comment]
its tdm 360 horse archery patch

**Comment by legendzwolf** [comment]
i think it makes  like a horsebehavior thing

**Comment by legendzwolf** [comment]
![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/68744110/65b03c01-fb2a-43ea-b70b-fb87da6cc44c)

**Comment by legendzwolf** [comment]
for now i will just disable it

**Comment by Monitor144hz** [comment]
Ok, I'll look into it.

**Comment by legendzwolf** [comment]
it happens again with other patches

**Comment by legendzwolf** [comment]
scar, precision, payload interpreter, mco

**Comment by Monitor144hz** [comment]
Redownload and reinstall Pandora

**Comment by legendzwolf** [comment]
WARN : Dispatcher > "SCAR" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Validator > defaultfemale~magicbehavior > Duplicate Variable > iState_NPCSneaking > REMOVED
WARN : Validator > defaultfemale~magicmountedbehavior > Duplicate Variable > iState_NPCSneaking > REMOVED
WARN : Validator > defaultfemale~mt_behavior > Duplicate Event > idleFreaSorrowLoopEnter > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > Collision_Start > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > PIE > REMOVED
INFO : Mod 1 : Attack - Modern Combat Overhaul - v.1.0.0
INFO : Mod 2 : Precision - v.1.0.0
INFO : Mod 3 : Payload Interpreter - v.1.0.0
INFO : Mod 4 : SCAR - v.1.0.0
INFO : Mod 5 : True Directional Movement - Procedural Leaning - v.1.0.0
INFO : Mod 6 : True Directional Movement - Headtracking - v.1.0.0
INFO : Mod 7 : Pandora Base - v.1.0.0

**Comment by Monitor144hz** [comment]
Make sure the XPMSE patch is completely disabled, including the mod, not just the patch being unticked. Also ensure that antivirus isn't interfering.

**Comment by legendzwolf** [comment]
does work for you?

**Comment by Monitor144hz** [comment]
I have no idea apart from this, like I said, I cannot reproduce this on my system. Please also ensure that Pandora is not conflicting with an old version and that Nemesis engine is disabled along with creature compatibility.

**Comment by Monitor144hz** [comment]
> does it work for you?

Yes. I am using all the mods you have and it works fine.

**Comment by legendzwolf** [comment]
im running se

**Comment by Monitor144hz** [comment]
Are you on Vortex or MO2?

**Comment by legendzwolf** [comment]
mo2

**Comment by Monitor144hz** [comment]
Can you test on a new clean profile with nothing but Pandora and a few other behavior mods?

**Comment by Monitor144hz** [comment]
And are you sure you have Pandora installed and run from within MO2 as an exe?

**Comment by legendzwolf** [comment]
![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/68744110/a918b1e1-c767-471f-a70a-4df78677c2de)

**Comment by legendzwolf** [comment]
![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/68744110/48bdda24-712c-4b68-8095-dae50edf5379)

**Comment by Monitor144hz** [comment]
I recommend you set the option "Create files in mod instead of overwrite" to true and have a separate empty output mod for Pandora, just like Nemesis. That way it is easier to troubleshoot the output files. After this, please test on a clean profile with nothing but Pandora and a few behaviour mods active.

**Comment by Monitor144hz** [comment]
Oh, I also recommend clearing out your overwrite folder to remove any loose files that may be interfering

**Comment by legendzwolf** [comment]
with xp32 enabled

**Comment by Monitor144hz** [comment]
Shouldn't matter but test without that enabled first.

**Comment by legendzwolf** [comment]
![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/68744110/c7cbbe89-c2b2-4d3e-a585-2a65dc1374e6)

**Comment by legendzwolf** [comment]
still not working

**Comment by Monitor144hz** [comment]
Can you zip up the output folder and send it here as an attachment?

**Comment by legendzwolf** [comment]
[pandora output.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13335346/pandora.output.zip)

**Comment by legendzwolf** [comment]
this one?

**Comment by legendzwolf** [comment]
and all npc disappear

**Comment by legendzwolf** [comment]
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2023 11 13 - 14 52 53 09](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/68744110/d3e5b3da-86d2-47a8-989e-f21a2df2cf2f)

**Comment by Monitor144hz** [comment]
```
        <hkcstring>Animations\NickNak\hort_Fwd.hkx</hkcstring>
        <hkcstring>Animations\NickNak\hort_Bwd.hkx</hkcstring>
        <hkcstring>Animations\NickNak\hort_Left.hkx</hkcstring>
        <hkcstring>Animations\NickNak\hort_Right.hkx</hkcstring>
        <hkcstring>Animations\NickNak\hort_FwdtoRight.hkx</hkcstring>
        <hkcstring>Animations\NickNak\hort_FwdtoLeft.hkx</hkcstring>
        <hkcstring>Animations\NickNak\hort_FwdtoBwd.hkx</hkcstring>
        <hkcstring>Animations\NickNak\hort_RighttoFwd.hkx</hkcstring>
        <hkcstring>Animations\NickNak\hort_RighttoLeft.hkx</hkcstring>
        <hkcstring>Animations\NickNak\hort_RighttoBwd.hkx</hkcstring>
        <hkcstring>Animations\NickNak\hort_BwdtoFwd.hkx</hkcstring>
        <hkcstring>Animations\NickNak\hort_BwdtoLeft.hkx</hkcstring>
        <hkcstring>Animations\NickNak\hort_BwdtoRight.hkx</hkcstring>
        <hkcstring>Animations\NickNak\hort_LefttoFwd.hkx</hkcstring>
        <hkcstring>Animations\NickNak\hort_LefttoRight.hkx</hkcstring>
        <hkcstring>Animations\NickNak\hort_LefttoBwd.hkx</hkcstring>
```
Where are these added animations from? There's no nicknak mod active in the logs or the screenshot

**Comment by legendzwolf** [comment]
idk i could stream it to you in discord

**Comment by legendzwolf** [comment]
its from tdm

**Comment by legendzwolf** [comment]
![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/68744110/8c858ae8-8994-4507-9e56-c800b509e5a2)

**Comment by Monitor144hz** [comment]
Can you try deleting the animationsetdatasinglefile and animationdatasinglefile in the output after running Pandora? Only thing I could think of from looking at the output. I am not at home so I can't vc right now.

**Comment by Monitor144hz** [comment]
Ok so I will take a closer look when I have time at home. Judging by the files I can see there doesn't seem to be anything weird, but it must be something with the behaviour output. Hang tight, and I'll narrow it down on my end. Thanks for providing the information^^

**Comment by Monitor144hz** [comment]
@legendzwolf what is your system language set to?

**Comment by Monitor144hz** [comment]
Cultures that use a comma in place of a decimal point are outputted wrongly by the export library, often messing up the blender generators and causing them to break totally, leading to invisibility and other issues. Really dumb mistake, and the exact same one I made in my first ever C# program, fix coming soon 

```xml
<!-- Culture: ind -->
    <hkobject name="#0116" class="hkbBlenderGenerator" signature="0x22df7147">
      <!--memSizeAndFlags SERIALIZE_IGNORED-->
      <!--referenceCount SERIALIZE_IGNORED-->
      <hkparam name="variableBindingSet">null</hkparam>
      <!--cachedBindables SERIALIZE_IGNORED-->
      <!--areBindablesCached SERIALIZE_IGNORED-->
      <hkparam name="userData">0</hkparam>
      <hkparam name="name">MT_Jump_SprintBlend</hkparam>
      <!--id SERIALIZE_IGNORED-->
      <!--cloneState SERIALIZE_IGNORED-->
      <!--padNode SERIALIZE_IGNORED-->
      <hkparam name="referencePoseWeightThreshold">0,000000</hkparam>
      <hkparam name="blendParameter">1000000,000000</hkparam>
      <hkparam name="minCyclicBlendParameter">0,000000</hkparam>
      <hkparam name="maxCyclicBlendParameter">1000000,000000</hkparam>
      <hkparam name="indexOfSyncMasterChild">-1</hkparam>
      <hkparam name="flags">0</hkparam>
      <hkparam name="subtractLastChild">false</hkparam>
      <hkparam name="children" numelements="2">#0117 #0119</hkparam>
      <!--childrenInternalStates SERIALIZE_IGNORED-->
      <!--sortedChildren SERIALIZE_IGNORED-->
      <!--endIntervalWeight SERIALIZE_IGNORED-->
      <!--numActiveChildren SERIALIZE_IGNORED-->
      <!--beginIntervalIndex SERIALIZE_IGNORED-->
      <!--endIntervalIndex SERIALIZE_IGNORED-->
      <!--initSync SERIALIZE_IGNORED-->
      <!--doSubtractiveBlend SERIALIZE_IGNORED-->
    </hkobject>
    ```
    
    
    
```xml
<!-- culture: en-US -->
     <hkobject name="#0116" class="hkbBlenderGenerator" signature="0x22df7147">
      <!--memSizeAndFlags SERIALIZE_IGNORED-->
      <!--referenceCount SERIALIZE_IGNORED-->
      <hkparam name="variableBindingSet">null</hkparam>
      <!--cachedBindables SERIALIZE_IGNORED-->
      <!--areBindablesCached SERIALIZE_IGNORED-->
      <hkparam name="userData">0</hkparam>
      <hkparam name="name">MT_Jump_SprintBlend</hkparam>
      <!--id SERIALIZE_IGNORED-->
      <!--cloneState SERIALIZE_IGNORED-->
      <!--padNode SERIALIZE_IGNORED-->
      <hkparam name="referencePoseWeightThreshold">0.000000</hkparam>
      <hkparam name="blendParameter">1.000000</hkparam>
      <hkparam name="minCyclicBlendParameter">0.000000</hkparam>
      <hkparam name="maxCyclicBlendParameter">1.000000</hkparam>
      <hkparam name="indexOfSyncMasterChild">-1</hkparam>
      <hkparam name="flags">0</hkparam>
      <hkparam name="subtractLastChild">false</hkparam>
      <hkparam name="children" numelements="2">#0117 #0119</hkparam>
      <!--childrenInternalStates SERIALIZE_IGNORED-->
      <!--sortedChildren SERIALIZE_IGNORED-->
      <!--endIntervalWeight SERIALIZE_IGNORED-->
      <!--numActiveChildren SERIALIZE_IGNORED-->
      <!--beginIntervalIndex SERIALIZE_IGNORED-->
      <!--endIntervalIndex SERIALIZE_IGNORED-->
      <!--initSync SERIALIZE_IGNORED-->
      <!--doSubtractiveBlend SERIALIZE_IGNORED-->
    </hkobject>
    
```

**Comment by legendzwolf** [comment]
yes it works now i have my windows in german
