### ISSUE TITLE
Can pandora support “GENDER Specific Animations” patches please?

### ISSUE THREAD

**Issue by AntimonyF5** [Monitor144hz/Pandora-Behaviour-Engine-Plus#100]
Because currently many DAR and OAR animations use female folders to differentiate between male and female animations. Although I know I can add the IsFemale() function to differentiate between male and female actions, I still hope pandora can support this patch. Nemesis has this patch.

**Comment by Monitor144hz** [comment]
No, use OAR or DAR.
