### ISSUE TITLE
Issues patching past 1.0

### ISSUE THREAD

**Issue by elbadcode** [Monitor144hz/Pandora-Behaviour-Engine-Plus#101]
Had been on 1.0 with 98% of my animations working, tried 1.1.3 and simply could not get a patch to produce anything other than 0_master. No conflicts and past versions were disabled. Now I'm trying 1.1.5 and it does produce all the files and has only minor errors in the log that would indicate a successful patch but in-game it's all T-poses. This one could be an MO2 issue but I thought I should raise the concern anyway. I also could not patch successfully when I reverted to 1.0, not sure if there's another case of the patcher deleting files or if I changed too much since I last successfully patched.

I'll see if I can work through this stuff myself but I figured this thread can serve as an ongoing hub for anyone else who successfully used Pandora before but can't after recent updates

**Comment by Monitor144hz** [comment]
Can you check v1.1.6 @elbadcode ?

**Comment by elbadcode** [comment]
appreciate the ping. Issue is unchanged on one mo2 setup but on another setup that had the same issue it resolved, although it still fails to patch specific behavior files if it has to overwrite. Don't understand how the other list is failing to load behaviors when it could load them from my pandora 1.0 output a few days ago but its probably an mo2 quirk not pandora
