### ISSUE TITLE
Patch for “Precision” not working in pandora 1.1.6

### ISSUE THREAD

**Issue by AntimonyF5** [Monitor144hz/Pandora-Behaviour-Engine-Plus#104]
This issue does not exist in 1.1.5，Now I can't attack the ground and high places

**Comment by Monitor144hz** [comment]
Cannot reproduce because of limited information. [Read this](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development#bug-reports) @AntimonyF5

**Comment by AntimonyF5** [comment]
> Cannot reproduce because of limited information. [Read this](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development#bug-reports) @AntimonyF5

Here is the log:
INFO : Skyrim Patcher 1.1.6-alpha
WARN : Dispatcher > "Scriptfree staggerlock" > defaultmale~0_master > Replace > Element > #0260/event/Element0/id > FAILED
INFO : Pandora Mod 1 : Precision - v.1.0.0
INFO : Pandora Mod 2 : Scriptfree staggerlock - v.1.0.0
INFO : Pandora Mod 3 : XPMSE Patch For Pandora - v.1.0.0
INFO : Pandora Mod 4 : SideSaddle combat spine fixer - v.1.0.0
INFO : Pandora Mod 5 : Pandora Base - v.1.0.0

It looks like the "Precision" patch has been generated, but I don't have the patch functionality in the game. However, this didn't happen in version 1.1.5.

**Comment by AntimonyF5** [comment]
> Cannot reproduce because of limited information. [Read this](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development#bug-reports) @AntimonyF5

More specifically，“﻿The included Nemesis behavior patch adds a pitch modifier to the actor's upper body while attacking, so you can aim your attacks up and down. ”which is the author of mod “precision” exact words.(https://www.nexusmods.com/skyrimspecialedition/mods/72347)

The functionality of this patch doesn't work in version 1.1.6, and because of that I haven't tested for any other issues.

**Comment by AntimonyF5** [comment]
> Cannot reproduce because of limited information. [Read this](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development#bug-reports) @AntimonyF5

Here is the output log：
B:\SkyrimSE\data\meshes\actors\character\characters female\defaultfemale.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\0_Master.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\magicbehavior.hkx
B:\SkyrimSE\data\meshes\actors\character\characters\defaultmale.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\magicmountedbehavior.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\staggerbehavior.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\horsebehavior.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\1hm_behavior.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\1hm_locomotion.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\bashbehavior.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\blockbehavior.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\bow_direction_behavior.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\crossbow_direction_behavior.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\idlebehavior.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\magic_readied_direction_behavior.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\mt_behavior.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\shout_behavior.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\shoutmounted_behavior.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\sprintbehavior.hkx
B:\SkyrimSE\data\meshes\actors\character\Behaviors\weapequip.hkx
B:\SkyrimSE\data\meshes\actors\atronachstorm\Behaviors\AtronachStormBehavior.hkx
B:\SkyrimSE\data\meshes\actors\atronachflame\Behaviors\AtronachFlameBehavior.hkx
B:\SkyrimSE\data\meshes\actors\atronachfrost\Behaviors\AtronachFrostBehavior.hkx
B:\SkyrimSE\data\meshes\actors\cow\Behaviors\H-CowBehavior.hkx
B:\SkyrimSE\data\meshes\actors\deer\Behaviors\DeerBehavior.hkx
B:\SkyrimSE\data\meshes\actors\dlc01\chaurusflyer\Behaviors\CHaurusFlyerBehavior.hkx
B:\SkyrimSE\data\meshes\actors\bear\Behaviors\BearBehavior.hkx
B:\SkyrimSE\data\meshes\actors\chaurus\Behaviors\ChaurusBehavior.hkx
B:\SkyrimSE\data\meshes\actors\canine\Behaviors\DogBehavior.hkx
B:\SkyrimSE\data\meshes\actors\canine\Behaviors Wolf\WolfBehavior.hkx
B:\SkyrimSE\data\meshes\actors\dlc02\dwarvenballistacenturion\Behaviors\BCBehavior.hkx
B:\SkyrimSE\data\meshes\actors\dlc02\benthiclurker\Behaviors\BenthicLurkerBehavior.hkx
B:\SkyrimSE\data\meshes\actors\dlc02\netch\Behaviors\NetchBehavior.hkx
B:\SkyrimSE\data\meshes\actors\dlc02\hmdaedra\Behaviors\HMDaedra.hkx
B:\SkyrimSE\data\meshes\actors\dlc02\boarriekling\Behaviors\BoarBehavior.hkx
B:\SkyrimSE\data\meshes\actors\dlc01\vampirebrute\Behaviors\VampireBruteBehavior.hkx
B:\SkyrimSE\data\meshes\actors\atronachfrost\characters\atronachfrostcharacter.hkx
B:\SkyrimSE\data\meshes\actors\dlc02\riekling\Behaviors\RieklingBehavior.hkx
B:\SkyrimSE\data\meshes\actors\atronachstorm\characters\atronachstormcharacter.hkx
B:\SkyrimSE\data\meshes\actors\dlc02\dwarvenballistacenturion\characters\ballistacenturion.hkx
B:\SkyrimSE\data\meshes\actors\dlc02\netch\characters\netchcharacter.hkx
B:\SkyrimSE\data\meshes\actors\cow\characters\h_cowcharater.hkx
B:\SkyrimSE\data\meshes\actors\atronachflame\characters\atronachflame.hkx
B:\SkyrimSE\data\meshes\actors\dlc02\hmdaedra\characters\hmdaedracharacter.hkx
B:\SkyrimSE\data\meshes\actors\dlc01\chaurusflyer\characters\chaurusflyercharacter.hkx
B:\SkyrimSE\data\meshes\actors\dlc02\boarriekling\characters\boar.hkx
B:\SkyrimSE\data\meshes\actors\deer\characters\deercharater.hkx
B:\SkyrimSE\data\meshes\actors\dlc02\benthiclurker\characters\benthiclurkercharacter.hkx
B:\SkyrimSE\data\meshes\actors\dlc02\scrib\Behaviors\ScribBehavior.hkx
B:\SkyrimSE\data\meshes\actors\dragon\Behaviors\DragonBehavior.hkx
B:\SkyrimSE\data\meshes\actors\dlc01\vampirebrute\characters\vampirebrutecharacter.hkx
B:\SkyrimSE\data\meshes\actors\dragonpriest\Behaviors\Dragon_Priest.hkx
B:\SkyrimSE\data\meshes\actors\dlc02\scrib\characters\scrib.hkx
B:\SkyrimSE\data\meshes\actors\chaurus\characters\chaurus.hkx
B:\SkyrimSE\data\meshes\actors\bear\characters\bearcharacter.hkx
B:\SkyrimSE\data\meshes\actors\dwarvenspherecenturion\Behaviors\SCBehavior.hkx
B:\SkyrimSE\data\meshes\actors\draugr\Behaviors\DraugrBehavior.hkx
B:\SkyrimSE\data\meshes\actors\dragonpriest\characters\dragon_priest.hkx
B:\SkyrimSE\data\meshes\actors\dwarvensteamcenturion\Behaviors\SteamBehavior.hkx
B:\SkyrimSE\data\meshes\actors\dwarvenspider\Behaviors\DwarvenSpiderBehavior.hkx
B:\SkyrimSE\data\meshes\actors\dwarvenspherecenturion\characters\spherecenturion.hkx
B:\SkyrimSE\data\meshes\actors\dwarvenspider\characters\dwarvenspidercenturion.hkx
B:\SkyrimSE\data\meshes\actors\dragon\characters\dragontest.hkx
B:\SkyrimSE\data\meshes\actors\dwarvensteamcenturion\characters\dwarvensteam.hkx
B:\SkyrimSE\data\meshes\actors\frostbitespider\Behaviors\FrostbiteSpiderBehavior.hkx
B:\SkyrimSE\data\meshes\actors\falmer\Behaviors\FalmerBehavior.hkx
B:\SkyrimSE\data\meshes\actors\hagraven\Behaviors\HavgravenBehavior.hkx
B:\SkyrimSE\data\meshes\actors\frostbitespider\characters\frostbitespidercharacter.hkx
B:\SkyrimSE\data\meshes\actors\giant\Behaviors\GiantBehavior.hkx
B:\SkyrimSE\data\meshes\actors\canine\characters wolf\wolf.hkx
B:\SkyrimSE\data\meshes\actors\canine\characters dog\dog.hkx
B:\SkyrimSE\data\meshes\actors\dlc02\riekling\characters\rieklingcharacter.hkx
B:\SkyrimSE\data\meshes\actors\horker\Behaviors\HorkerBehavior.hkx
B:\SkyrimSE\data\meshes\actors\hagraven\characters\hagravencharacter.hkx
B:\SkyrimSE\data\meshes\actors\draugr\characters\draugr.hkx
B:\SkyrimSE\data\meshes\actors\draugr\characterskeleton\draugr_skeleton.hkx
B:\SkyrimSE\data\meshes\actors\icewraith\Behaviors\IceWraithBehavior.hkx
B:\SkyrimSE\data\meshes\actors\horker\characters\horker.hkx
B:\SkyrimSE\data\meshes\actors\mammoth\Behaviors\MammothBehavior.hkx
B:\SkyrimSE\data\meshes\actors\icewraith\characters\icewraithcharacter.hkx
B:\SkyrimSE\data\meshes\actors\horse\Behaviors\HorseBehavior.hkx
B:\SkyrimSE\data\meshes\actors\slaughterfish\Behaviors\SlaughterfishBehavior.hkx
B:\SkyrimSE\data\meshes\actors\skeever\Behaviors\SkeeverBehavior.hkx
B:\SkyrimSE\data\meshes\actors\sabrecat\Behaviors\SabreCatBehavior.hkx
B:\SkyrimSE\data\meshes\actors\mammoth\characters\mammothcharacter.hkx
B:\SkyrimSE\data\meshes\actors\giant\characters\giantcharacter.hkx
B:\SkyrimSE\data\meshes\actors\slaughterfish\characters\slaughterfish.hkx
B:\SkyrimSE\data\meshes\actors\falmer\characters\falmer.hkx
B:\SkyrimSE\data\meshes\actors\skeever\characters\skeevercharacter.hkx
B:\SkyrimSE\data\meshes\actors\sabrecat\characters\sabrecat.hkx
B:\SkyrimSE\data\meshes\actors\spriggan\Behaviors\SprigganBehavior.hkx
B:\SkyrimSE\data\meshes\actors\troll\Behaviors\TrollBehavior.hkx
B:\SkyrimSE\data\meshes\actors\werewolfbeast\Behaviors\WerewolfBehavior.hkx
B:\SkyrimSE\data\meshes\actors\spriggan\characters\spriggan.hkx
B:\SkyrimSE\data\meshes\actors\ambient\chicken\Behaviors\ChickenBehavior.hkx
B:\SkyrimSE\data\meshes\actors\ambient\hare\Behaviors\HareBehavior.hkx
B:\SkyrimSE\data\meshes\actors\ambient\chicken\characters\chickencharater.hkx
B:\SkyrimSE\data\meshes\actors\ambient\hare\characters\harecharater.hkx
B:\SkyrimSE\data\meshes\actors\horse\characters\horse.hkx
B:\SkyrimSE\data\meshes\actors\troll\characters\troll.hkx
B:\SkyrimSE\data\meshes\actors\werewolfbeast\characters\werewolf.hkx
B:\SkyrimSE\data\meshes\actors\goat\Behaviors\GoatBehavior.hkx
B:\SkyrimSE\data\meshes\actors\goat\characters\goatcharater.hkx
B:\SkyrimSE\data\meshes\actors\wisp\Behaviors\WispBehavior.hkx
B:\SkyrimSE\data\meshes\actors\vampirelord\Behaviors\VampireLord.hkx
B:\SkyrimSE\data\meshes\actors\wisp\characters\wispcharacter.hkx
B:\SkyrimSE\data\meshes\actors\vampirelord\characters\vampirelord.hkx

**Comment by Monitor144hz** [comment]
Zip up all your Pandora output and send it here.

**Comment by AntimonyF5** [comment]
> Zip up all your Pandora output and send it here.

It seems to be fixed in 1.1.7α
