### ISSUE TITLE
Not an issue - A question

### ISSUE THREAD

**Issue by jungleoper** [Monitor144hz/Pandora-Behaviour-Engine-Plus#105]
Is it possible to install nemesis and use the patches that come with it from within Pandora?
Speaking of Proper Spell Cast Direction and Retimed Hit Frame

**Comment by Monitor144hz** [comment]
Yes, Nemesis comes with bundled behavior patches. Copy those into a separate mod, and Pandora should detect those. Use the discussion section next time to ask a question.
