### ISSUE TITLE
Not sure if a Pandora Bug or a Mod Issue

### ISSUE THREAD

**Issue by MaskPlague** [Monitor144hz/Pandora-Behaviour-Engine-Plus#106]
[Thick Thighs Take Lives](https://www.nexusmods.com/skyrimspecialedition/mods/78465?tab=description) doesn't trigger when Pandora is used instead of Nemesis.
The engine log has no info so I assume it would be a mod issue, is that correct? According to the Mod Author "Early versions of pandora were tested with [Thick Thighs Take Lives] and [it] worked" but since the first time I tried (back in 0.9.1 of Pandora) it hasn't worked for me. 

Whole log:
INFO : Skyrim Patcher 1.1.5-alpha
INFO : Pandora Mod 1 : SnuSnu - v.1.0.0
INFO : Pandora Mod 2 : XPMSE Patch For Pandora - v.1.0.0
INFO : Pandora Mod 3 : Pandora Base - v.1.0.0

**Comment by Monitor144hz** [comment]
So I think there have been some misunderstandings. The version of Pandora that TTTL is describing is an old iteration of Pandora, the very first prototype that was prone to a lot of errors and instability. 

It is not compatible with the current version of Pandora for now (#76), but I'm sure NickNak can port it easily as the process isn't difficult.
