### ISSUE TITLE
Hot Key Skill

### ISSUE THREAD

**Issue by Gonzeh** [Monitor144hz/Pandora-Behaviour-Engine-Plus#107]
When trying to run Pandora with the Hot Key Skill mod enabled it just closes.

**Comment by Monitor144hz** [comment]
Cannot reproduce on latest version. [Read this and revise the issue to include more information. ](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development#bug-reports)

**Comment by Monitor144hz** [comment]
@Gonzeh

**Comment by Gonzeh** [comment]
So sorry for wasting your time! I was using 1.1.6 but a build from last week. Works perfect on the newest version.
