### ISSUE TITLE
Critical Error 

### ISSUE THREAD

**Issue by Kazyachka** [Monitor144hz/Pandora-Behaviour-Engine-Plus#108]
This was not the case in older versions of Pandora.
![Untitled](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/150479122/a24cd805-639b-4d5e-8e24-c9dd1642b7e9)

**Comment by Monitor144hz** [comment]
More information please. Engine.log and output files.

**Comment by Kazyachka** [comment]
[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14200188/Engine.log)

**Comment by YnzeH22** [comment]
I had the same problem, disabling "Ultimate Combat Creature Compatibility" fixed it for me.

**Comment by Kazyachka** [comment]
> I had the same problem, disabling "Ultimate Combat Creature Compatibility" fixed it for me.

trank you
