### ISSUE TITLE
crash with  many animations

### ISSUE THREAD

**Issue by legendzwolf** [Monitor144hz/Pandora-Behaviour-Engine-Plus#11]

**Comment by Kazyachka** [comment]
@legendzwolf 

Can you tell us more? And send the log

**Comment by legendzwolf** [comment]
theres is no log it just closes

**Comment by Kazyachka** [comment]
> theres is no log it just closes

Strange, it closes (crashes) after you select animations and press Launch?

**Comment by legendzwolf** [comment]
yeah and i have mo2 and pandora as exclusion in windows

**Comment by Kazyachka** [comment]
> > theres is no log it just closes
> 
> Strange, it closes (crashes) after you select animations and press Launch?

I had the same problem in the past. But it was resolved after update 0.4.2

**Comment by Kazyachka** [comment]
@legendzwolf 

It’s easier to update to version 0.4.2 now and see if the problem is solved. Since I am not a native English speaker and my system is in Russian. There was such an error, it was related to languages ​​and was solved in 0.4.2

**Comment by Monitor144hz** [comment]
needs more info like the last time; output zipped and sent, with sc of active patches

**Comment by Kazyachka** [comment]
> needs more info like the last time; output zipped and sent, with sc of active patches

Again, the same problem most likely lies precisely in this. His system is in a different language and the latest version he installed is 0.3.0. I think that I will not be mistaken in saying that there is a bug in this version. And the symptoms are exactly the same as mine, namely: Crash after pressing Launch, without a log.

**Comment by Monitor144hz** [comment]
Cannot assume it is the case. Also he updated to 0.4.2 in #10 to which it was resolved. So I am guessing it is a separate issue

**Comment by Monitor144hz** [comment]
Closed for lack of information - high probability of false report from recent off-platform interactions
