### ISSUE TITLE
Pandora not detecting mods

### ISSUE THREAD

**Issue by DarklyNightly** [Monitor144hz/Pandora-Behaviour-Engine-Plus#112]
### Version

latest

### Provide Instructions on Reproducing the Problem

install it like a mod then run it

### Provide Relevant Files

[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14274304/Engine.log)

### Provide Visual Proof (optional)

![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/75499681/1c0e4420-f1a3-4c35-bbde-c7ffae3100da)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
What exactly is the issue here? Is it not detecting mods?

**Comment by DarklyNightly** [comment]
> What exactly is the issue here? Is it not detecting mods?

yes

**Comment by DarklyNightly** [comment]
it was working fine before i purged and redeployed the links in nexus

**Comment by DarklyNightly** [comment]
![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/75499681/26799825-f778-4dc2-92b6-1f33ad10052b)
is this a valid path?

**Comment by Monitor144hz** [comment]
It shouldn't start in a nested folder, it should either start in the Data folder directly **or** in the Vortex mods folder, assuming Vortex automtically syncs the output files from there later.

**Comment by DarklyNightly** [comment]
it doesnt work in the vortex mods folder

**Comment by Gildedter** [comment]
having the same issue, the deployed Pandora doesn't contain the exe, so in Vortex I pointed it to the staging folder instead.
