### ISSUE TITLE
[Bug]: Pandora crashes with MG's Creature Overhaul v1.1.2 and above's Troll patch active

### ISSUE THREAD

**Issue by imanoobyasu0** [Monitor144hz/Pandora-Behaviour-Engine-Plus#116]
### Version

v1.1.5-alpha

### Provide Instructions on Reproducing the Problem

Tested on three different version of ModdingGuild's creature overhaul mod, v1.1.1, v1.1.2, and v1.2.0.
The patch provided by v1.1.1, "Troll - Distar experience" doesnt crash pandora when active, but v1.1.2 and v1.2.0's patch does.
Difference between v1.1.1 and the higher versions is:
"Nemesis patch for Trolls | Troll conversion to OAR | Troll esp converted to espfe | Now fully compatible with Precision Creatures | Nemesis Creatures Behavior Compatibility added as requirement"
That was added for v1.1.2.
Didnt even seem to have a problem with this back in v1.0.0-alpha of pandora.

### Provide Relevant Files

[Pandora Output.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14321472/Pandora.Output.zip)

### Provide Visual Proof (optional)

![Screenshot 2024-02-18 152035](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/155877008/8299dc88-e7aa-43a4-99e2-826295e62fd5)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
> v1.1.5-alpha

Reproducible on v1.1.5-alpha but not present in v1.1.6-alpha. Update the engine files.
