### ISSUE TITLE
[Bug]: Crouch Sliding

### ISSUE THREAD

**Issue by Pet9948** [Monitor144hz/Pandora-Behaviour-Engine-Plus#119]
### Version

v1.1.6

### Provide Instructions on Reproducing the Problem

The generator produces a lot of errors.. It’s especially strange that it breaks: Crouch Sliding mod. He no longer has a tackle. This problem was not observed on Nemesis.

### Provide Relevant Files

[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14357280/Engine.log)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by elbadcode** [comment]
Try this: https://www.nexusmods.com/skyrimspecialedition/mods/112320
Anything that adds movement predating AMR is likely to have issues without a patch
