### ISSUE TITLE
I can't cast spells...

### ISSUE THREAD

**Issue by Kliqerav** [Monitor144hz/Pandora-Behaviour-Engine-Plus#12]
Hello, first of all, thank you for the great work, I wish you a full life of happiness.

My case is as follows. I switched from Nemesis to Pandora recently but I have a strange problem when I turn on the True Directional Movement - Head Tracking patch, I simply cannot cast spells with just one hand, for example if I have spells in both of the character's hands and try to cast with the left mouse button the spell does not come out despite a slight change in the animation, the same happens if I try to cast just by pressing the right mouse button, however if I have spells in both of the character's hands and press and hold the button first right mouse button and then the left mouse button I can cast the spell in the character's left hand, if I press and hold first the left button and then the right button I get the same result as trying to cast it with one hand.

Returning to Nemesis everything works normally, disabling the patch as well.

This problem also happens with NPCs but only playable races, Draugr, for example, can still cast spells normally.

I'll attach the output folder for each one if you want to take a look:
[Pandora Output patch off.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13452174/Pandora.Output.patch.off.zip)
[Pandora Output patch on.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13452176/Pandora.Output.patch.on.zip)

I'll list some things I've already tried:
- I'm using the latest version of Pandora, 0.4.2.
- I've already tried redownloading and reinstalling Pandora.
- I already completely cleaned the Pandora output folder, just to be sure.
- I have already redownloaded the game.
- I'm using Skyrim version 1.5.97 with Skyrim Lite Loader.
- I did a test without the TDM plugin.
- I did a test with only the following mods installed:
1. 	SKSE
2. 	Address Library for SKSE Plugins
3. 	SkyUI
4. 	UIExtensions
5. 	PapyrusUtil SE - Modders Scripting Utility Functions
6. 	MCM Helper
7. 	TrueHUD - HUD Additions
8. 	True Directional Movement - Modernized Third Person Gameplay

Additionally, I have another problem not related to the one above, when I have many animation mods (many Ostim addons) installed, Pandora closes about 5 seconds after clicking Launch, this is a secondary problem for me and less relevant since I can only reduce the quantity. In this case, Pandora does not produce a log.
After many tests I realized that sometimes it is possible to complete the process with a considerable amount of mods but this seems almost random, for example, I managed to generate a ptach with 59 animation mods without Pandora closing but this is rare and in most cases attempts Pandora closes when trying to launch with the same 59 mods. The most I've ever achieved is 60.
I converted all FNIS mods in my modlist with the [Animlist Transition Tool](https://github.com/Monitor144hz/AnimlistTransitionTool), if relevant.
I'll attach the output here if you want to take a look:
[Pandora Output - 59 - Fail.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13452962/Pandora.Output.-.59.-.Fail.zip)
[Pandora Output - 59 - Success.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13452963/Pandora.Output.-.59.-.Success.zip)
[Pandora Output - 60 - Sucesss.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13452964/Pandora.Output.-.60.-.Sucesss.zip)

My OS is Windows 10, Brazilian Portuguese.
I have .NET Desktop Runtime 7.0.14 (x64), .Net Desktop Runtime 6.0.25 (x86 and x64) and .NET SDK 8.0.100 (x64).

If you need any more information, please let me know.

**Comment by Monitor144hz** [comment]
Thank you for the detailed report, I will investigate the cause of both issues.

**Comment by Kazyachka** [comment]
@Kliqerav 

Please tell me friend, how did you make the patch? Can you explain to me

**Comment by Kliqerav** [comment]
> @Kliqerav
> 
> Please tell me friend, how did you make the patch? Can you explain to me
> 
> Every time I select FNIS list txt I get an error. And again it seems to me that it is related to language
 
Do you mean how I converted the FNIS mods in my modlist with the Animlist Transition Tool?
If so, I can try to make a small tutorial, it wasn't very difficult actually.

**Comment by Kazyachka** [comment]
> > @Kliqerav
> > Please tell me friend, how did you make the patch? Can you explain to me
> > Every time I select FNIS list txt I get an error. And again it seems to me that it is related to language
> 
> Do you mean how I converted the FNIS mods in my modlist with the Animlist Transition Tool? If so, I can try to make a small tutorial, it wasn't very difficult actually.

Yes, and it’s better for me to tell it or, more precisely, write it. Since I speak English poorly. I am Russian and have only two languages ​​to my credit: Russian and Ukrainian. And it will be difficult for me to understand without translation. (Google translator partially solves this problem) But the most important mistake is not the task, it’s loading the Fnis list after which a red error message appears

**Comment by Kliqerav** [comment]
> > > @Kliqerav
> > > Please tell me friend, how did you make the patch? Can you explain to me
> > > Every time I select FNIS list txt I get an error. And again it seems to me that it is related to language
> > 
> > 
> > Do you mean how I converted the FNIS mods in my modlist with the Animlist Transition Tool? If so, I can try to make a small tutorial, it wasn't very difficult actually.
> 
> Yes, and it’s better for me to tell it or, more precisely, write it. Since I speak English poorly. I am Russian and have only two languages ​​to my credit: Russian and Ukrainian. And it will be difficult for me to understand without translation. (Google translator partially solves this problem) But the most important mistake is not the task, it’s loading the Fnis list after which a red error message appears

I understand, unfortunately I don't think I can help if that's the case, for me an error message doesn't appear when I try to load a FNIS_*_list.txt file, it simply loads.

**Comment by Kazyachka** [comment]
> > > > @Kliqerav
> > > > Please tell me friend, how did you make the patch? Can you explain to me
> > > > Every time I select FNIS list txt I get an error. And again it seems to me that it is related to language
> > > 
> > > 
> > > Do you mean how I converted the FNIS mods in my modlist with the Animlist Transition Tool? If so, I can try to make a small tutorial, it wasn't very difficult actually.
> > 
> > 
> > Yes, and it’s better for me to tell it or, more precisely, write it. Since I speak English poorly. I am Russian and have only two languages ​​to my credit: Russian and Ukrainian. And it will be difficult for me to understand without translation. (Google translator partially solves this problem) But the most important mistake is not the task, it’s loading the Fnis list after which a red error message appears
> 
> I understand, unfortunately I don't think I can help if that's the case, for me an error message doesn't appear when I try to load a FNIS_*_list.txt file, it simply loads.

Why can’t you, I think you will help me completely 1. by telling me what your windows interface language is 2. By making a detailed guide you will help not only me but also other people

**Comment by Monitor144hz** [comment]
Please don't hijack the thread, this is for **discussion of the issue only**, not a place to request tech support or help.

**Comment by Kazyachka** [comment]
> Please don't hijack the thread, this is for **discussion of the issue only**, not a place to request tech support or help.

Of course, I apologize for perhaps some rudeness or excessive directness, but.. I will not take over this topic if you work on problems in your mods/applications. I asked a question but I haven’t received an answer for more than two days and I’ll be able to get it later

https://github.com/Monitor144hz/AnimlistTransitionTool/issues/5#issue-comment-box

**Comment by Monitor144hz** [comment]
@Kazyachka 

>I will not take over this topic if you work on problems in your mods/applications

>I asked a question but I haven’t received an answer for more than two days

I think you misunderstood, I have priorities for my work and these are all projects that I undertake in my free time as a hobby, not a commitment. Also, what I said was not a negotiable suggestion.

For that separate issue, you can wait for me to get around to it or do it yourself, but it does not mean you can override this thread for your own benefit. It has barely been a day since you posted that, I am not active every day of the week to respond instantly, and it does not mean I did not see it before.

Either contribute to the topic, or stay out of it and stop impeding my work please.

**Comment by Monitor144hz** [comment]
Thank you for your detailed report and testing!

**Comment by Kazyachka** [comment]
> @Kazyachka
> 
> > I will not take over this topic if you work on problems in your mods/applications
> 
> > I asked a question but I haven’t received an answer for more than two days
> 
> I think you misunderstood, I have priorities for my work and these are all projects that I undertake in my free time as a hobby, not a commitment. Also, what I said was not a negotiable suggestion.
> 
> For that separate issue, you can wait for me to get around to it or do it yourself, but it does not mean you can override this thread for your own benefit. It has barely been a day since you posted that, I am not active every day of the week to respond instantly, and it does not mean I did not see it before.
> 
> Either contribute to the topic, or stay out of it and stop impeding my work please.

@Monitor144hz 

You most likely misunderstood, I know that you have priority for Pandora fashion and I’m not rushing you (I didn’t say that I need a fix here and now) I would just like to know the essence of this problem. I'm not trying to slow you down at work. And we don’t know the essence of this problem; maybe this problem is not in the language at all. And yes, I understand that you don’t look at the threads every day, I just drew your attention to this. And if I pointed out the problem to you, this is not a reason to send me to hell (even in a polite manner). You are behaving in a cultural manner, at a minimum. I apologize again if I caused you any inconvenience.

**Comment by zyf2008Neptune** [comment]
The problem is still in 0.6.1, and some animations in immersive interactions won't play.

**Comment by Monitor144hz** [comment]
Reopened, as it seems to be recurring issue. Working on finding cause. Any relevant info is appreciated.

**Comment by Monitor144hz** [comment]
I've found the cause, but the fix is not simple. Expect some time before I can find a proper solution.

**Comment by Monitor144hz** [comment]
Cause is different and specific so topic was moved to a separate issue #25
