### ISSUE TITLE
[Bug]: Troll Distar Experience Patch from ModdingGuild Creature Overhaul Crashes Pandora v1.1.7a

### ISSUE THREAD

**Issue by imanoobyasu0** [Monitor144hz/Pandora-Behaviour-Engine-Plus#124]
### Version

v1.1.7-alpha

### Provide Instructions on Reproducing the Problem

When running pandora, if the troll distar experience patch is enabled, pandora crashes no matter what after running for a few seconds.

### Provide Relevant Files

[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14395252/Engine.log)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
v1.1.8 fixes this problem
