### ISSUE TITLE
[Bug]: Dual magic casting problems

### ISSUE THREAD

**Issue by Yrbaa** [Monitor144hz/Pandora-Behaviour-Engine-Plus#125]
### Version

Pandora Behaviour Engine v1.1.7-alpha

### Provide Instructions on Reproducing the Problem

Dual magic casting while walking doesn't play the correct animation (walk is overwriting it?) there is a small twitch but that's it. The animations work fine when standing still.
I have tried two magic casting animation mods and the problem persisted.

### Provide Relevant Files

[Engine.log.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14395257/Engine.log.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
@Yrbaa was this problem present in the last version? If you're using XPMSE, do you have the patch required?

**Comment by Yrbaa** [comment]
Oh, the XPMSE patch worked flawlessly, everything is in working order. Thanks =D
