### ISSUE TITLE
[Bug]: Falmer cannot use staves or magic

### ISSUE THREAD

**Issue by Yrbaa** [Monitor144hz/Pandora-Behaviour-Engine-Plus#135]
### Version

Pandora Behaviour Engine v1.1.8-alpha

### Provide Instructions on Reproducing the Problem

Hi! The Falmer in my game that have staves equipped cannot use them. They are walking around and sometimes doing the t-pose, they neither can use magic. The normal falmer with swords etc work fine it's just specifically the ones that use staves, also tested with nemesis and they work fine with it.

### Provide Relevant Files

[Engine.log.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14470416/Engine.log.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Jetster17** [comment]
I'm getting the same problem with version 1.2.2.
![Uploading Screenshot68.png…]()

**Comment by Landohlakes** [comment]
contact nemesis and get it restarted
