### ISSUE TITLE
[Bug]: CTD on main menu load with Xing No Art Behavior

### ISSUE THREAD

**Issue by A1kowo** [Monitor144hz/Pandora-Behaviour-Engine-Plus#141]
### Version

v1.2.1a

### Provide Instructions on Reproducing the Problem

pandora generates successfully, however, launching Skyrim through mo2 crashes before main menu buttons are drawn. Disabling xing no art behavior has no crash. Using 0.8b of xing no art behavior.
CTD confirmed using xing no art + new staff school (https://www.nexusmods.com/skyrimspecialedition/mods/88670?tab=description) on a minimal LO (only requirements for those mods)
No log to post because menu does not draw, let me know if there's  a way to force a log :)

### Provide Relevant Files

[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14551867/Engine.log)
[Pandora minimum Output.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14551868/Pandora.minimum.Output.zip)

### Provide Visual Proof (optional)

![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/105258530/9d7cc656-3b33-43c3-82b6-204713a404d2)
minimum load order which showed rash

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by imanoobyasu0** [comment]
worked for me

**Comment by A1kowo** [comment]
Apologies, was offline
Works for me, tysm for the fix :)
