### ISSUE TITLE
[Bug]: CGO Dodge Roll with No Momentum (Plus a couple other errors)

### ISSUE THREAD

**Issue by viiuan** [Monitor144hz/Pandora-Behaviour-Engine-Plus#143]
### Version

1.2.1a

### Provide Instructions on Reproducing the Problem

I generate as normal using Pandora, with Pandora Base, Animated Mounted Casting, Precision, CGO, Horse Riding Improvements, Horse Pose Improvements, and MBO selected.
Generating the same behaviour files on Nemesis without Horse Riding/Pose Improvements works 100% fine, but I'm not sure if the removal of that mod correlates.
Dodge animation plays but my character has zero momentum for the duration of the animation.

### Provide Relevant Files

It looks like there were errors with Animated Mounted Casting and MBO, but I'm not sure how that relates to the CGO dodge. You guys are the experts here, so if anyone would like to explain to me why that would be neat.

[Engine.log.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14566338/Engine.log.zip)

### Provide Visual Proof (optional)

![ezgif-1-3aa239d193](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/63260365/e89909ee-3f54-4f8b-b516-72b685cb2799)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
See #28

**Comment by viiuan** [comment]
ahh ok! thanks for the info.
