### ISSUE TITLE
cant see patch

### ISSUE THREAD

**Issue by legendzwolf** [Monitor144hz/Pandora-Behaviour-Engine-Plus#15]
https://www.nexusmods.com/skyrimspecialedition/mods/97674

**Comment by Monitor144hz** [comment]
![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/89633536/70d2cefe-30bf-429c-a3a6-87566413def0)
![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/89633536/2c3dd15e-97ed-435f-ae7e-d9510698c9e1)


latest version on my end, user error
