### ISSUE TITLE
[Bug]: TPose with Ultimate Dragons Nemesis Patch

### ISSUE THREAD

**Issue by matteoharrauer** [Monitor144hz/Pandora-Behaviour-Engine-Plus#151]
### Version

1.2.2 Alpha

### Provide Instructions on Reproducing the Problem

With enable :

- Ultimate Dragon SE 2.55
- Nemesis Creatures BEHAVIOUR compatibility v1.3

The initial quest not start, Alduin not coming .
Game Version :Skyrim Se 1.5.97 .
If remove the Pandora Output all work well.

### Provide Relevant Files

[PANDORA_OUT.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14653025/PANDORA_OUT.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
Investigating, seems to be issue with dragon behavior

**Comment by matteoharrauer** [comment]
THX for your investigation.
I did a new test in this order .

- Clean Pandora output
- Unistall Ultimate dradon
- Re-install Nemesis Creatures BEHAVIOUR compatibility without support for Ultimate Dragon
- Re run Pandora
Now work perfect.
At the end Pandora fix all my animation and behaviour...so bye bye Ultimate Dragon, i will re-test with the next release.
Thx for your job!!
