### ISSUE TITLE
[Bug]: problems with animations Devious Devices 5 2

### ISSUE THREAD

**Issue by NeaBessy** [Monitor144hz/Pandora-Behaviour-Engine-Plus#152]
Pandora 1.2.2

### Provide Instructions on Reproducing the Problem

my Pandora 1 2 2 does not handle animations from [ Devious Devices 5 2.  [https://amlgames.com/files/file/1861-devious-devices-seaevr/?ysclid=lu0049wshn377158758](url)
More precisely, it processes them, but not all of them

The character's hands should be inserted into the armbinder, but they are free (the animation of the idle does not work).. When the character tries to free himself, the animation works and his hands are inserted into the armbinder, 
When using  FNIS everything works correctly

### Provide Relevant Files

[Pandora OUTUT.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14669181/Pandora.OUTUT.zip)
[saves.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14669517/saves.zip)
[modlist.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14669616/modlist.zip)

### Provide Visual Proof (optional)

![0](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/72144983/a456e07c-219e-438e-b388-9a13c3eea3da)
![00](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/72144983/b5668591-b27a-456e-b6b1-a411540482cf)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by kirby86k** [comment]
> Pandora 1.2.2
> 
> ### Provide Instructions on Reproducing the Problem
> my Pandora 1 2 2 does not handle animations from [ Devious Devices 5 2. [https://amlgames.com/files/file/1861-devious-devices-seaevr/?ysclid=lu0049wshn377158758](url) More precisely, it processes them, but not all of them
> 
> The character's hands should be inserted into the armbinder, but they are free (the animation of the idle does not work).. When the character tries to free himself, the animation works and his hands are inserted into the armbinder, When using FNIS everything works correctly
> 
> ### Provide Relevant Files
> [Pandora OUTUT.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14669181/Pandora.OUTUT.zip) [saves.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14669517/saves.zip) [modlist.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14669616/modlist.zip)
> 
> ### Provide Visual Proof (optional)
> ![0](https://private-user-images.githubusercontent.com/72144983/314570840-a456e07c-219e-438e-b388-9a13c3eea3da.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjI4NjUsIm5iZiI6MTcxMTAyMjU2NSwicGF0aCI6Ii83MjE0NDk4My8zMTQ1NzA4NDAtYTQ1NmUwN2MtMjE5ZS00MzhlLWIzODgtOWExM2MzZWVhM2RhLkdJRj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEyMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYjIyNjZhNmI3MzU1ODZlOTUyNmQ5NGJhYjE3Mzg4N2VmZWQxZTM5ZGE4YTEzNTAxY2RhNjg1MDY0YzBiNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sJDxZrO6defP5AnprEam-ef0XsUxRGu5vMwatNsTC4Q) [ ![0](https://private-user-images.githubusercontent.com/72144983/314570840-a456e07c-219e-438e-b388-9a13c3eea3da.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjI4NjUsIm5iZiI6MTcxMTAyMjU2NSwicGF0aCI6Ii83MjE0NDk4My8zMTQ1NzA4NDAtYTQ1NmUwN2MtMjE5ZS00MzhlLWIzODgtOWExM2MzZWVhM2RhLkdJRj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEyMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYjIyNjZhNmI3MzU1ODZlOTUyNmQ5NGJhYjE3Mzg4N2VmZWQxZTM5ZGE4YTEzNTAxY2RhNjg1MDY0YzBiNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sJDxZrO6defP5AnprEam-ef0XsUxRGu5vMwatNsTC4Q) ](https://private-user-images.githubusercontent.com/72144983/314570840-a456e07c-219e-438e-b388-9a13c3eea3da.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjI4NjUsIm5iZiI6MTcxMTAyMjU2NSwicGF0aCI6Ii83MjE0NDk4My8zMTQ1NzA4NDAtYTQ1NmUwN2MtMjE5ZS00MzhlLWIzODgtOWExM2MzZWVhM2RhLkdJRj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEyMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYjIyNjZhNmI3MzU1ODZlOTUyNmQ5NGJhYjE3Mzg4N2VmZWQxZTM5ZGE4YTEzNTAxY2RhNjg1MDY0YzBiNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sJDxZrO6defP5AnprEam-ef0XsUxRGu5vMwatNsTC4Q) [ ](https://private-user-images.githubusercontent.com/72144983/314570840-a456e07c-219e-438e-b388-9a13c3eea3da.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjI4NjUsIm5iZiI6MTcxMTAyMjU2NSwicGF0aCI6Ii83MjE0NDk4My8zMTQ1NzA4NDAtYTQ1NmUwN2MtMjE5ZS00MzhlLWIzODgtOWExM2MzZWVhM2RhLkdJRj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEyMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYjIyNjZhNmI3MzU1ODZlOTUyNmQ5NGJhYjE3Mzg4N2VmZWQxZTM5ZGE4YTEzNTAxY2RhNjg1MDY0YzBiNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sJDxZrO6defP5AnprEam-ef0XsUxRGu5vMwatNsTC4Q) ![00](https://private-user-images.githubusercontent.com/72144983/314570880-b5668591-b27a-456e-b6b1-a411540482cf.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjI4NjUsIm5iZiI6MTcxMTAyMjU2NSwicGF0aCI6Ii83MjE0NDk4My8zMTQ1NzA4ODAtYjU2Njg1OTEtYjI3YS00NTZlLWI2YjEtYTQxMTU0MDQ4MmNmLkdJRj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEyMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYTAyZjBlNDZlNWI2ZTUyZDUxYWUxYmZlZjJkYTMxMTkwMjEzOWIzNzVkMzViNjRkZjViMjJlMGRlZDAxNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RHu9H-uIg7GDLY5g6amQTgCPF5evec6BP1lRxKsmEhY) [ ![00](https://private-user-images.githubusercontent.com/72144983/314570880-b5668591-b27a-456e-b6b1-a411540482cf.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjI4NjUsIm5iZiI6MTcxMTAyMjU2NSwicGF0aCI6Ii83MjE0NDk4My8zMTQ1NzA4ODAtYjU2Njg1OTEtYjI3YS00NTZlLWI2YjEtYTQxMTU0MDQ4MmNmLkdJRj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEyMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYTAyZjBlNDZlNWI2ZTUyZDUxYWUxYmZlZjJkYTMxMTkwMjEzOWIzNzVkMzViNjRkZjViMjJlMGRlZDAxNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RHu9H-uIg7GDLY5g6amQTgCPF5evec6BP1lRxKsmEhY) ](https://private-user-images.githubusercontent.com/72144983/314570880-b5668591-b27a-456e-b6b1-a411540482cf.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjI4NjUsIm5iZiI6MTcxMTAyMjU2NSwicGF0aCI6Ii83MjE0NDk4My8zMTQ1NzA4ODAtYjU2Njg1OTEtYjI3YS00NTZlLWI2YjEtYTQxMTU0MDQ4MmNmLkdJRj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEyMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYTAyZjBlNDZlNWI2ZTUyZDUxYWUxYmZlZjJkYTMxMTkwMjEzOWIzNzVkMzViNjRkZjViMjJlMGRlZDAxNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RHu9H-uIg7GDLY5g6amQTgCPF5evec6BP1lRxKsmEhY) [ ](https://private-user-images.githubusercontent.com/72144983/314570880-b5668591-b27a-456e-b6b1-a411540482cf.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjI4NjUsIm5iZiI6MTcxMTAyMjU2NSwicGF0aCI6Ii83MjE0NDk4My8zMTQ1NzA4ODAtYjU2Njg1OTEtYjI3YS00NTZlLWI2YjEtYTQxMTU0MDQ4MmNmLkdJRj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEyMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYTAyZjBlNDZlNWI2ZTUyZDUxYWUxYmZlZjJkYTMxMTkwMjEzOWIzNzVkMzViNjRkZjViMjJlMGRlZDAxNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RHu9H-uIg7GDLY5g6amQTgCPF5evec6BP1lRxKsmEhY)
> 
> ### Contributing To Development
> * [x]  I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

If you want a temporary fix:
Install Devious Devices NG+, it transfers all the animations to OAR and makes DD a lot lighter.

**Comment by NeaBessy** [comment]
> Если вам нужно временное исправление: Установите Devious Devices NG, он перенесет всю анимацию в OAR и сделает DD намного легче.



> If you want a temporary fix: Install Devious Devices NG, it transfers all the animations to OAR and makes DD a lot lighter.

Thank you. It helped me and now everything is working
