### ISSUE TITLE
[Bug]: Crouch Sliding Mod doesnt work

### ISSUE THREAD

**Issue by XarisZ** [Monitor144hz/Pandora-Behaviour-Engine-Plus#156]
### Version

1.2.2

### Provide Instructions on Reproducing the Problem

Download both the Engine and the [mod](https://www.nexusmods.com/skyrimspecialedition/mods/39157?tab=files), tick/run Pandora and test ingame.
I tried to recreate it with Nemesis and it worked so i know something is wrong with PE.
When that happens with Nemesis the fix is to delete the cache. I tried the same with PE and it didnt do anything.
I should also point out that changing the priority in the engine didnt do anything.

### Provide Relevant Files

[Pandora_Output.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14746090/Pandora_Output.zip)

### Provide Visual Proof (optional)

https://imgur.com/a/gsEZfi0

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
https://www.nexusmods.com/skyrimspecialedition/mods/112320

@XarisZ
