### ISSUE TITLE
[Bug]: MCO cannot be patched

### ISSUE THREAD

**Issue by Roidtakor** [Monitor144hz/Pandora-Behaviour-Engine-Plus#157]
### Version

1.2.2a

### Provide Instructions on Reproducing the Problem

Pandora aborts patching of MCO 1.6.0.6. with the message. "CRITICAL FAILURE 

If the cause is unknown: submit a report to the author of the engine and attach Engine.log
Launch aborted. Existing output was not cleared, and current patch list will not be saved."

I just ticked MCO for testing and nothing else.

Skyrim 1.6.640

### Provide Relevant Files

[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14763580/Engine.log)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
Unreproducible so far. Have you tried reinstalling both MCO and Pandora?

**Comment by Roidtakor** [comment]
I was almost desperate, because everybody else can patch MCO with Pandora. So after some time I found out, that the mod Jump Attack has overwritten one single file of MCO. As I'd disabled Jump Attack Pandora has patched MCO in less than 1 sec. I'm sorry for wasting your time.

**Comment by elbadcode** [comment]
This was previously addressed in another issue, though I'm not sure if its mentioned anywhere else. You have to take that one file from jumpingattack and change 10 to 8 both in the file name and inside the text itself for it to work with the latest few versions of MCO

**Comment by Monitor144hz** [comment]
oh right, I had an overwrite packaged for that in earlier versions but it got deleted along with the sweeping changes to the new pandora format. I'll restore it soon

**Comment by Monitor144hz** [comment]
https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues/47#issuecomment-1873468727
@Roidtakor here's the fix if you still want to use jump attack.  

I've decided against including the fix in pandora as it's too volatile to change, and isn't the engine's area of responsibility.

**Comment by Roidtakor** [comment]
@Monitor221hz thank you.
