### ISSUE TITLE
Engine not recognizing current .NET

### ISSUE THREAD

**Issue by HHC2437** [Monitor144hz/Pandora-Behaviour-Engine-Plus#159]
Hi there, apologies if this may be the wrong place. New to Github.

Anyhoo, I am trying to get this Pandora Behavior Engine to work and I've updated the .NET through the link you posted on your main page. Though it doesn't specifiy if anything else other than the older version of 7.0.0.0 is okay to use. I've tried 7.0.0.0 and the latest version, restarted my pc twice and this engine is still unable to recognize my updated .NET, causing the program to not start properly.

I have the mod installed properly within MO2, it has an empty mod folder attached to it for anything it generates and I've tried running MO2 and Pandora Behavior Engine Plus as Admin, and nothing I've done has worked.

The only error the program shows when it is run, is that it says my .NET isn't installed/updated which still would be incorrect.

I've no idea what to do now and writing this in hopes I can get some help on fixing this.

Thank you

**Comment by Monitor144hz** [comment]
@HHC2437 that is how .NET versions work. There's no guarantee that .NET 8 or 9 will work with a project requiring .NET 7. Just use .NET 7.x.x.

**Comment by HHC2437** [comment]
Thank you two very much for your help! Installing the Visual Studio 2022 version fixed the issue and the Pandora engine runs flawlessly now. Thanks
