### ISSUE TITLE
[Bug]: SCAR Mod doesnt work

### ISSUE THREAD

**Issue by GaryjackYzee** [Monitor144hz/Pandora-Behaviour-Engine-Plus#162]
### Version

V1.2.2 - Alpha

### Provide Instructions on Reproducing the Problem

Download both the Engine and the [mod](https://www.nexusmods.com/skyrimspecialedition/mods/72014?tab=files) tick/run Pandora and test ingame.
I tried to recreate it with Nemesis and it worked so i know something is wrong with PE.
When that happens with Nemesis the fix is to delete the cache. I tried the same with PE and it didnt do anything.
It work wrong with "SCAR_1hmReadyDummy.hkx".

### Provide Relevant Files

[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14810543/Engine.log)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
@GaryjackYzee are you sure this isn't because you are not using a SCAR compatible moveset?

**Comment by kirby86k** [comment]
It should work, it's a moveset which is incompatible for you. For me, it works perfectly with the cheming1122 sets (all three of them).

**Comment by GaryjackYzee** [comment]
OK.Thank you.
