### ISSUE TITLE
[Bug]: Magic issues

### ISSUE THREAD

**Issue by jackson8541** [Monitor144hz/Pandora-Behaviour-Engine-Plus#163]
### Version

v1.2.2-alpha

### Provide Instructions on Reproducing the Problem

（1）Stealth casting does not work （2）When the left hand is equipped with spells and idle, there is no animation on the left hand

### Provide Relevant Files

[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14817226/Engine.log)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
@jackson8541 if you're using XPMSE you need to have the patch enabled
