### ISSUE TITLE
No output is being generated

### ISSUE THREAD

**Issue by Txikivasco** [Monitor144hz/Pandora-Behaviour-Engine-Plus#17]
using MO2 v2.5.0 no output is generated to the overwrite, and using a dedicated mod instead neither works. Am I doing something wrong?

**Comment by Txikivasco** [comment]
Yes, from within MO2, but nevermind, It's working now. 

I didn't uninstall the previous Pandora version and the files were being messed up. My bad.

**Comment by spddqd** [comment]
Hello! Sorry if I'm hijacking this issue I have the same problem, but I never used Pandora before. It generates no Engine.log. MO2 is 2.4.3
Here's the output from the program:
```
Engine launched.
Launch finished in 3.3 seconds
Resources loaded successfully.
Mod 1 : Precision - v.1.0.0
Mod 2 : Combat Gameplay Overhaul SE - v.1.0.0
Mod 3 : Eating Animations and Sounds SE - v.1.0.0
Mod 4 : Payload Interpreter - v.1.0.0
Mod 5 : EVG Animated Traversal - v.1.0.0
Mod 6 : Jump Behavior Overhaul - v.1.0.0
Mod 7 : SBE - True Prone System - v.1.0.0
Mod 8 : Animation Teleport Bug Fix - v.1.0.0
Mod 9 : Pandora Base - v.1.0.0
```

**Comment by spddqd** [comment]
> @spddqd What version of Pandora is this?

Sorry for bothering you. I've reinstalled MO2 and created a new profile, which resolved the problem, behavior got generated, but I still don't see Engine.log being created. I suppose it is made if something goes wrong while engine is running? Using latest, 0.6.1-alpha.

**Comment by Monitor144hz** [comment]
Nope, Engine.log should generate no matter what the result is. Perhaps you should check Overwrite folder.

**Comment by Monitor144hz** [comment]
but it's clear that it seems to be user error. will be reclosing this, thanks for the report regardless

**Comment by spddqd** [comment]
> Nope, Engine.log should generate no matter what the result is. Perhaps you should check Overwrite folder.

I stand corrected once again. It was indeed generated in overwrite. I assumed that if I use redirection, it will also output it into the created mod.
Thank you for your work!
