### ISSUE TITLE
[Bug]: Creature HKX issue - Boar

### ISSUE THREAD

**Issue by lapsio** [Monitor144hz/Pandora-Behaviour-Engine-Plus#170]
### Version

1.2.2-alpha

### Provide Instructions on Reproducing the Problem

Running any SL animation involving Boar results in not working animation. Creature animation doesn't start at all. Player animates properly. Realigning actors with hotkey doesn't help.

Issue does not occur with FNIS behaviors. Additionally replacing boarbehavior.hkx generated by Pandora with one generated by FNIS solves issue (even if Pandora is used in-game globally).

No new animation packs have been installed since issue #158 so build log is the same as previously.

### Provide Relevant Files

[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14844090/Engine.log)

[boar_behaviors.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14844077/boar_behaviors.zip)

fnis_boarbehavior.hkx was generated by FNIS
pandora_BoarBehavior.hkx was generated by Pandora

### Provide Visual Proof (optional)

*trust me bro*

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
Check [this build](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/actions/runs/8530421514) to see if the issue is fixed please. Download artifact is at the bottom of the page.

**Comment by lapsio** [comment]
doesn't seem to help. Chaurus also doesn't work, I uploaded new .hkx generated by Pandora to Chaurus issue but now it seems that it doesn't work the same way as Boar (not animating at all)

[BoarBehavior.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14844890/BoarBehavior.zip)

**Comment by lapsio** [comment]
bump
