### ISSUE TITLE
[Bug]: A lot of mistakes

### ISSUE THREAD

**Issue by oren19737373** [Monitor144hz/Pandora-Behaviour-Engine-Plus#179]
### Version

Pandora Behaviour Engine v1.3.0-alpha

### Provide Instructions on Reproducing the Problem

A lot of mistakes

### Provide Relevant Files

[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14861626/Engine.log)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Horf** [comment]
Can at least confirm the 'Pandora Base' (dragonbehavior) errors with version 1.3 of Pandora
```
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/maxAnkleHeightMS > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/hipIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/kneeIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/ankleIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/isPlantedMS > FAILED
```

**Comment by Monitor144hz** [comment]
warnings =/= bugs

**Comment by mjadu** [comment]
[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14941534/Engine.log)
