### ISSUE TITLE
[Bug]:  The Ultimate Dodge Mod Reborn (TUDM)

### ISSUE THREAD

**Issue by Jacksop9999** [Monitor144hz/Pandora-Behaviour-Engine-Plus#181]
### Version

v1.3.0-alpha

### Provide Instructions on Reproducing the Problem

The Ultimate Dodge Mod Reborn doesn't show up in the Launcher, and the dodge key just doesn't work in game. 
TUDM is displayed if I turn on Nemesis in MO2. But in the game, when I press the dodge key, the character rolls in place.

### Provide Relevant Files

[Pandora_Output.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14895064/Pandora_Output.zip)

### Provide Visual Proof (optional)

![1](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/166257748/adbf6d96-1f65-4337-a23b-a949a3d2600a)
![2](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/166257748/6c7209a1-42dc-4bd0-9fc2-75d1dab0fbfd)
![3](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/166257748/499d22be-8fa8-4851-8455-31bbecab83e2)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by MaskPlague** [comment]
A workaround to this is copy only the "tudm" folder and its contents in Nemesis's /Nemesis_Engine/mod/tudm to the same path in Pandora and then allow the TUDM xing Patch to overwrite that. There is currently no Patch included in Pandora for TUDM so you need to copy the one from Nemesis.

**Comment by Jacksop9999** [comment]
Yes, it helped to see TUDM in Pandora, but the animations are not working now as I understood the patch is only on TkDodge. Also in Engine.log I noticed bugs regarding Flinching Animations and yes, in the game on deer and wolves does not work shooting animation. Looks like we’re going back to Nemesis.

**Comment by MaskPlague** [comment]
Huh, following all the above steps makes it work completely for me, odd.
