### ISSUE TITLE
[Bug]: Certain Kill Moves are not working

### ISSUE THREAD

**Issue by Jetster17** [Monitor144hz/Pandora-Behaviour-Engine-Plus#187]
### Version

v1.3.0-alpha

### Provide Instructions on Reproducing the Problem

I'm unsure if this is a problem with Pandora, but I noticed during some testing, some of the cinematic kill moves aren't working. The animations will start but almost immediately stop, leaving the enemies alive and unable to even be hit for a few seconds thereafter. I did some testing with Violens and a couple of the one-handed and most of the two-handed kill moves are broken like this. The worst part is I'm not sure what the culprit is. I've uploaded what is hopefully the Engine Log and the Engine Output.

### Provide Relevant Files

[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14954016/Engine.log)
[Pandora_Engine.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14954084/Pandora_Engine.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by theedward1** [comment]
Thanks for sharing this issue, I was having trouble finding out why my killmoves weren't working, I can confirm that it is definitely a Pandora problem. Disabling Pandora fixed the issue and killmoves are now working.

**Comment by Monitor144hz** [comment]
I've found the issue, thanks. should be fixed in next version

**Comment by Monitor144hz** [comment]
Please check v1.4.0-alpha and reopen if the bug is not fixed
