### ISSUE TITLE
[Bug]: Immersive Equipment Animations - only boots equip animation working with Pandora

### ISSUE THREAD

**Issue by theedward1** [Monitor144hz/Pandora-Behaviour-Engine-Plus#188]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v1.3.0-alpha

### Provide Instructions on Reproducing the Problem

https://www.nexusmods.com/skyrimspecialedition/mods/77187?tab=description

Download mod and try to equip items, only the boots animations work. Comments and bug reports are in the mod page as well.

### Provide Relevant Files

[Pandora Output.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14973534/Pandora.Output.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by DJLegends1011** [comment]
duplication of
[https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues/76](url)

**Comment by Monitor144hz** [comment]
duplicate of #76 as DJ mentioned
