### ISSUE TITLE
Some issues with Precision, Payload interpreter, TK Dodge RE, Extra Drawing Animations and Weapon Styles for IED.

### ISSUE THREAD

**Issue by Kliqerav** [Monitor144hz/Pandora-Behaviour-Engine-Plus#19]
Hello, I'm here again. How have you been? I hope you are well.

I've been doing some testing over the last few days using versions 0.5.0 and 0.6.1, now I'm going to report some problems I had.

Firstly we have a problem with the Extra Drawing Animations mod, the animations do not work as they should when the mod is marked on Pandora, the same happens with the version included in the Weapon Styles mod - Draw-Sheathe animations for IED. When I try to use any of them with Pandora, the drawing animations while making the character move forward produce a bug where the character's legs don't move even though he is moving as he should, it's as if he is sliding on ice, for lack of a better term. Furthermore, the drawing animation itself is not reproduced correctly, for example, if I have a shield and a sword equipped, the character only plays the sword-drawing animation.

In the case of Extra Drawing Animations I have yet another problem, when the character is standing still he plays the animation of placing the shield on his back even without any shield equipped.

I can confirm that both work well with Nemesis.

In the first test, the only mods installed were SKSE and Extra Drawing Animations, as this has no requirements.

In the second test I installed the following mods:

1. SKSE
2. Address Library for SKSE Plugins
3. Animation Queue Fix
4. Paired Animation Improvements
5. Open Animation Replacer
6. Open Animation Replacer - IED Conditions
7. Simple Dual Sheath
8. Immersive Equipment Displays
9. Weapon Styles - DrawSheathe Animations for IED

I'll leave the respective outputs here if you want to take a look:

[Pandora Output - Extra Drawing Animations.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13573855/Pandora.Output.-.Extra.Drawing.Animations.zip)
[Pandora Output - Weapon Styles.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13573856/Pandora.Output.-.Weapon.Styles.zip)

Now let's move on to the second problem.

This time it's Precision, when equipping a spell in either hand, or both hands, of the character and trying to “drawing” it, so to speak, I receive a CTD.

The funny thing is that if I install Precision + TK Dodge RE, whether or not I check the patch for TK Dodge RE in Precision, I don't get a CTD, however I have the problem again when casting spells that I described in #12, I can't cast spells unless I hold down the right button and then the left button. Furthermore, the character's movement is quite uncontrolled, if I do say so myself. While I make the character walk with the spells in his hands, he doesn't stop even after I let go of the keyboard, and the character also starts to shake.

Since we are also talking about the TK Dodge RE I will report a small problem with it. When I'm using the TK Dodge SE's standard animations and press the key chosen for the Dodge, my character doesn't move even when playing the animation. If I use the Dynamic Dodge Animations mod (which I use by default), the problem disappears, perhaps because this mod uses Animation Motion Revolution.

In the first test I used the following mods:

1. SKSE
2. Crash Logger SSE (Since this combination led to a CTD I will attach the crash log together, maybe it will help something)
3. Address Library for SKSE Plugins
4. SSE Display Tweaks
5. SkyUI
6. MCM Helper
7. Animation Motion Revolution
8. Precision (Without the TK Dodge RE patch)

In the second test I used these:

1. SKSE
2. Address Library for SKSE Plugins
3. SSE Display Tweaks
4. SkyUI
5. MCM Helper
6. Animation Motion Revolution
7. IFrame Generator RE
8. Precision (With TK Dodge RE patch)
9. TK Dodge SE (Animations only)
10. TK Dodge RE (The standalone version)

In the third test these were:

1. SKSE
2. Address Library for SKSE Plugins
3. Animation Motion Revolution
4. IFrame Generator RE
5. TK Dodge SE (Animations only)
6. TK Dodge RE (The standalone version)

Here are the outputs:

[Pandora Output - Precision.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13573869/Pandora.Output.-.Precision.zip)
[Pandora Output - Precision + TK Dodge RE.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13573871/Pandora.Output.-.Precision.%2B.TK.Dodge.RE.zip)
[Pandora Output -  TK Dodge RE.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13573882/Pandora.Output.-.TK.Dodge.RE.zip)

Another mod that I found a problem with was Payload Interpreter, the problem is the same as Precision, when I equip a spell in the character's hand and try to “drawing” I get a CTD, if I install TK Dodge RE I don't get a CTD but I get the same bug mentioned above. Using the Nemesis Less Patch available on the Behavior Data Injector page instead of marking it on Pandora the problem disappears.

In the first test I used the following mods:

1. SKSE
2. Crash Logger SSE (I intend to include the crash log in the output)
3. Address Library for SKSE Plugins
4. Payload Interpreter

In the second test I used these:

1. SKSE
2. Address Library for SKSE Plugins
3. Payload Interpreter
4. IFrame Generator RE
5. TK Dodge SE (Animations only)
6. TK Dodge RE (The standalone version)

Here are the outputs:

[Pandora Output - Payload Interpreter.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13573887/Pandora.Output.-.Payload.Interpreter.zip)
[Pandora Output - Payload Interpreter + TK Dodge RE.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13573898/Pandora.Output.-.Payload.Interpreter.%2B.TK.Dodge.RE.zip)

Lastly, I'm not sure if I should call it a bug but I'll report it since I'm already here.
This time it has to do with the new version of Pandora XPMSE Patch, 0.6.0, if someone tries to use the patch with the Minimal or Basic version of XPMSSE they will receive the good old T Pose, the same applies if they try to use the Extended but replace the esp with the [Lite](https://www.nexusmods.com/skyrimspecialedition/mods/69583) version. The reason I'm not sure if I should classify it as a bug is simple, there should be no need to use it if you're not going to use the Extended version of XPMSSE (I guess), even taking into account that the old version, 0.3.2, didn't have this problem.
In this case, if it is not classified as a bug, I would suggest that a warning be placed somewhere appropriate. I say this because Nemesis does not differentiate between XPMSSE versions and always installs the patch, which can lead to confusion for someone trying to migrate from Nemesis to Pandora.

That's it for today, I hope I didn't take up too much of your time. If you need any more in-depth testing let me know.

My OS is Windows 10, Brazilian Portuguese.
I have .NET Desktop Runtime 7.0.14 (x64), .Net Desktop Runtime 6.0.25 (x86 and x64) and .NET SDK 8.0.100 (x64).

If you need any other relevant information let me know.

Thank you for your hard work, I wish you all the best.

**Comment by Monitor144hz** [comment]
@Kliqerav I split the thread into multiple issues, most of which are fixed. See #28 for information regarding TK Dodge RE. 


v0.6.9-alpha should fix the outstanding issues outlined here. Please update and let me know if there are any problems.

@spddqd tagging you too as you may want to update.
