### ISSUE TITLE
[Bug]: 2hw armblend do not apply to walking animation with battleaxes

### ISSUE THREAD

**Issue by MercuryXIII** [Monitor144hz/Pandora-Behaviour-Engine-Plus#190]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v1.3.0

### Provide Instructions on Reproducing the Problem

Problem: Battleaxes using greatsword walking animation, which look pretty bad, particularly if greatswords animation are significantly different. To my understanding, Skyrim combines 2hm animations with 2hw armblend for battleaxes\warhammer animations, but it does not accrue for some locomotion.

Solution: Switched back to Nemesis, run it with same mods — 2hm walking animation looks as intended. My assumption is that there are some issue with behavior generation related to blending these kinds of animations.

Note: Strangely enough, warhammer movement animations works properly with Pandora. On the other hand, I also noticed a similar issue with dual wield, particularly noticeable with animations that have reverse grip on a weapon. This issue also gone away after switching to Nemesis.
Other note — all of my tests were with animations added via OAR, not direct vanilla replaces. Also, I tested in Skyrim VR and cannot confirm if this applies to player character, I have only seen it with NPCs.

### Provide Relevant Files

[Pandora Output.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/15047292/Pandora.Output.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
@MercuryXIII are you using XPMSE? If so, do you have the XPMSE Patch for Pandora ticked?

**Comment by Monitor144hz** [comment]
> using greatsword walking animation, which look pretty bad, particularly if greatswords animation are significantly different

> Switched back to Nemesis, run it with same mods — 2hm walking animation looks as intended.

Is it possible for some form of image or short video to be provided so I can see exactly what the issue is? As the descriptors use here do not give me an idea of what's bad or good looking

**Comment by MercuryXIII** [comment]
Providing visual illustrations will be difficult. Images not going to help much, and normal way to capture the video is a bit problematic in VR. I probably can set it up, but it will take some research. Maybe I can try to describe it better?

For example — [Imperium Animation Pack](https://www.nexusmods.com/skyrimspecialedition/mods/88752) have greatsword resting on a shoulder during idle and locomotion. But battleaxes are held at waist level during these animations. And this how animation looks in mod showcase videos and in my game with Nemesis. 

With Pandora, walking animation with battleaxes still looks like animation for greatsword — with weapon resting on a shoulder. As a result, NPCs keep shifting the weapon from position on a shoulder (when they're walking) to position at waist level (during other animations). This is not intentional and quite noticeable with a large weapon, such as battleaxe.

**Comment by Monitor144hz** [comment]
So the issue here seems to be that some bone array changes from War Hammer and Battle Axe Movement Fix are not applied properly. I've found the cause so the fix should be pushed hopefully soon.

**Comment by Monitor144hz** [comment]
Should be fixed in v1.4.0-alpha
