### ISSUE TITLE
[Bug]: Pandora app crashes with Dragon Priest Fix - Behavior Overhaul

### ISSUE THREAD

**Issue by pPkMnh4to8994h** [Monitor144hz/Pandora-Behaviour-Engine-Plus#196]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v1.4.0-alpha

### Provide Instructions on Reproducing the Problem

Application crashes when trying to generate files with Dragon Priest Fix patch enabled. No error or anything.
Engine.log provides no error either, only warnings.
v1.3.0 generates files with no issues.

I'm not even sure if it should actually work as intended with Pandora...

### Provide Relevant Files

[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/15050595/Engine.log)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
Check v1.4.1-alpha
