### ISSUE TITLE
There are some issues with TK dodge RE and OStim Standalone

### ISSUE THREAD

**Issue by shawnpaker** [Monitor144hz/Pandora-Behaviour-Engine-Plus#20]
hello,First of all, I'd like to thank you for your contribution.But English is not my first language and you may have some difficulty reading it, I'll try to portray the problems I encountered.
TK dodges RE have an animation, but they just roll in place and don't displace.
Here is a list of combat mods
1.MCO
2.MaxsuBlockOverhaul
3.Dynamic Block Hit
4.Customized attacked animation repository
5.Precision
6.Elden Power Attack
7.SCAR - Skyrim Combos AI Revolution
8.True Directional Movement
And then there are the ones that may not matter. 
Another problem is that although ostim starts the animation from the beginning, there are some errors when switching animations, either staying in place or executing the wrong animation.
In addition to billy's furniture animation package, I also tried the animations that come with ostim, and I repeated the test between Pandora and Nemesis.
Immersive Interactions - Animated Actions and MCO seem to work fine, at the moment it's just the tk dodge RE that's experiencing some issues, EVG Animated Traversal I haven't tested it yet, so I'll let you know as much as I can if there's a problem.
I don't have creature animations installed, I use Nemesis almost exclusively and I'll go back and forth between Nemesis and Pandora.
Finally thank you very much for your contribution, I want Pandora to become better, I hope you understand what I mean, these sentences are from machine translation, my game version is downgraded 1.5.97 and my OS is win10 64 .

**Comment by shawnpaker** [comment]
Sorry I forgot to mention that the version of Pandora is v0.6.1-alpha.

**Comment by shawnpaker** [comment]
[Engine.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13602089/Engine.zip)
hi, regarding the ostim issue I've run a few more tests and this only seems to occur when I manually select the animation, I try to use ostim's auto mode the animation runs automatically but if I try to go back to manually selecting it, the animation seems to error out again.
I'll upload the log file this time and hopefully that will help you a bit.

**Comment by Monitor144hz** [comment]
investigating

**Comment by Monitor144hz** [comment]
Please post Engine.log

**Comment by shawnpaker** [comment]
[Engine.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13627658/Engine.zip)

**Comment by shawnpaker** [comment]
> 请发布引擎.log
[Engine.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13627662/Engine.zip)

**Comment by Monitor144hz** [comment]
@shawnpaker please try v0.6.9-alpha and let me know if issues are fixed, they were fixed on my end. And please read #28 for info about TK Dodge Standalone
