### ISSUE TITLE
Fail to build Dodge MCO-DXP animations [Bug]: 

### ISSUE THREAD

**Issue by ShRomses** [Monitor144hz/Pandora-Behaviour-Engine-Plus#200]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v1.4.0-alpha

### Provide Instructions on Reproducing the Problem

Failed to build with Dodge MCO-DXP, if I turn off Dodge, build is succesfull, in 1.3.0 version there no such issue

### Provide Relevant Files

[Pandora Output.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/15051884/Pandora.Output.zip)

### Provide Visual Proof (optional)

![Снимок](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/167687166/224334ba-b25f-4a6a-8fd6-16e070d0ac66)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
Resolved in v1.4.2-alpha
