### ISSUE TITLE
[Bug]: Critical failure with PSCD + TURN

### ISSUE THREAD

**Issue by DJ4ddi** [Monitor144hz/Pandora-Behaviour-Engine-Plus#202]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

1.4.2-alpha

### Provide Instructions on Reproducing the Problem

When using [Proper Spell Cast Direction](https://www.nexusmods.com/skyrim/mods/68794) and [Turning Animation Won't Affect UpperBody](https://www.nexusmods.com/skyrim/mods/85083) at the same time, a critical failure is reported. This combination worked fine with 1.3.0-alpha.

I use both patches as provided by Nemesis, but using the standalone patches linked above produced the same result.

Disabling either of the mods resolves the error.

### Provide Relevant Files

[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/15052518/Engine.log)

Active mods for reproduction:
```
pandora
xpmse
pscd
turn
```

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
Please test this debug build of Pandora to see if the issue is fixed.

https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/actions/runs/8805065194/artifacts/1440489288
