### ISSUE TITLE
[Bug]: Creating issue for Nemesis

### ISSUE THREAD

**Issue by akavkl** [Monitor144hz/Pandora-Behaviour-Engine-Plus#209]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v1.4.3_alpha

### Provide Instructions on Reproducing the Problem

Update engine with Nemesis with Pandora engine installed

### Provide Relevant Files

```
ERROR(2006): Missing behavior file. The behavior file name must be in this format ("Nemesis_<file name>.xml") and it must located in the same path as the hkx counterpart. Please contact the mod author
File: defaultfemale_character
```
Can't exclude Nemesis yet as without it all characters T-pose, and ignoring Nemesis and patching with Pandora doesn't help with the issue, and disabling Pandora works, no T-posing either.

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
Pandora is not meant to be active when you are using Nemesis. I cannot fix this issue. Use one engine or the other, not both.
