### ISSUE TITLE
[Bug]: Weird T-Posing Issue

### ISSUE THREAD

**Issue by setho123113** [Monitor144hz/Pandora-Behaviour-Engine-Plus#212]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v1.4.3-alpha

### Provide Instructions on Reproducing the Problem

Hello, I am having thie very weird issue regarding my player character. for some strange reason my player character is only in the T-Pose but even more strange is other in-game NPC's are not T-Posing. (Except My Character.)

### Provide Relevant Files

[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/15378748/Engine.log)

### Provide Visual Proof (optional)

![20240520110744_1](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/81538265/baa0b590-5813-42b2-bdef-fa647b93d6fe)
![20240520110747_1](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/81538265/5280b3b4-c2d2-4674-93fa-de803fea398b)
![20240520110751_1](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/81538265/896c42be-8b4d-4d35-b87f-5604d15738ee)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Kyationa** [comment]
is open animation replacer loading the animations that you have installed properly as this tends to happen when open animation replacer does not load all animations is most of the time one mod will cause it to not load animations i have had a simple armor mod break animations from loading .

**Comment by setho123113** [comment]
> is open animation replacer loading the animations that you have installed properly as this tends to happen when open animation replacer does not load all animations is most of the time one mod will cause it to not load animations i have had a simple armor mod break animations from loading .


I installed Open Animation Replacer just now and I tested it in game. and it crashed once I loaded a save game.

**Comment by Kyationa** [comment]
> > is open animation replacer loading the animations that you have installed properly as this tends to happen when open animation replacer does not load all animations is most of the time one mod will cause it to not load animations i have had a simple armor mod break animations from loading .
> 
> I installed Open Animation Replacer just now and I tested it in game. and it crashed once I loaded a save game.
> 
> (Update. I deleted Nemesis. and I believe that was causing the crashing issue due to my research on the topic at hand. but I still am having the T-Pose Issue unfortunately.)

huh try delete output for pandora and running it again

**Comment by Monitor144hz** [comment]
Gonna need more information, like the output files or such. I will say that in regards to being error-tolerant, Pandora does not check for incompatible animation files or missing behavior files (yet), both of which can cause TPose. So users must know what they are doing.

**Comment by setho123113** [comment]
> Gonna need more information, like the output files or such. I will say that in regards to being error-tolerant, Pandora does not check for incompatible animation files or missing behavior files (yet), both of which can cause TPose. So users must know what they are doing.

For now. I uninstalled Pandora Engine since it was causing too many issues for my game. even though you may not know the issue regarding this. I hope you will eventually find out what it is since the Pandora Engine is in it's Alpha Stage right now.

(And if any other users are having the same issue as I was.)

I wish you the best of luck regarding the Engine and I hope you improve it over time.

when Pandora Engine gets to be more stable. I'll take a look at it again and I'll see how it works for me in the end.

Thanks!

**Comment by Monitor144hz** [comment]
> For now. I uninstalled Pandora Engine since it was causing too many issues for my game. even though you may not know the issue regarding this. I hope you will eventually find out what it is since the Pandora Engine is in it's Alpha Stage right now.

Yeah so if you don't provide further information like output files I can't do anything about this. So I'm closing it for now.

**Comment by kanapuro** [comment]
fix is incredibly simple. make a new save, animations should be normal on that save. if so, just load back onto your current save. this refreshes open animation replacer (or whatever mod is acting up) and your game will be totally fine. woohoo yippee

**Comment by Watson153** [comment]
> > For now. I uninstalled Pandora Engine since it was causing too many issues for my game. even though you may not know the issue regarding this. I hope you will eventually find out what it is since the Pandora Engine is in it's Alpha Stage right now.
> 
> Yeah so if you don't provide further information like output files I can't do anything about this. So I'm closing it for now.

I have this issue the new save did not fix the issue can you help me?
