### ISSUE TITLE
Magic and staff don't work properly in third person

### ISSUE THREAD

**Issue by shawnpaker** [Monitor144hz/Pandora-Behaviour-Engine-Plus#22]
Hey ,man, how's it going? I learnt about this bug from other Pandora users and tried it myself, I found out that I can't use magic and wands and maybe magic scrolls in third person, I don't know what the reason for this is, when using it I can move but there are no magical effects or animations and it doesn't consume mana, whereas in first person everything works fine.

**Comment by Monitor144hz** [comment]
Duplicate of #12
