### ISSUE TITLE
[suggestion]: Publish to NexusMods

### ISSUE THREAD

**Issue by nashlyx** [Monitor144hz/Pandora-Behaviour-Engine-Plus#237]
### Expected behavior

This mod is very nice, but it is difficult for people to find this mod on github, so by publishing this mod on nexus and receiving feedback from various people, we can make this mod even better. thought.
Even in pre-alpha, it's worth posting to a very large community.

**Comment by nashlyx** [comment]
Even if it's pre-alpha

**Comment by Monitor144hz** [comment]
This engine will be posted to Nexus after it receives rudimentary support for furniture and arm offset animation mods like ZaZ and Immersive Interactions, which is also when it leaves Alpha and enters Beta

**Comment by nashlyx** [comment]
ok I hope this development goes well
