### ISSUE TITLE
Cannot use right hand after equipping magic. SSE ver 1.6.640, Pandora+ ver 0.6.1 and earlier

### ISSUE THREAD

**Issue by 1100-1-1101** [Monitor144hz/Pandora-Behaviour-Engine-Plus#24]
I am using pandora+ 0.6.1 but have had this issue since 0.4.2.

I can run Pandora+ and it works absolutely fine, but in game I have the following issue:
If I equip any weapon attacking with the right hand works fine but as soon as I equip magic (even if I do not leave the menu before unequipping) the right hand stops working.

I say right hand because the left hand appears to work regardless, and the control mapping for the right hand works in other contexts, such as the journal and inventory. I have tried switching to Nemesis for a new save and it works perfectly, so I am reasonably confident the issue lies in Pandora+. I have attached my modlist and load order for reference:

[modlist.txt](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13675860/modlist.txt)
[loadorder.txt](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13675864/loadorder.txt)
[pandora+ ActiveMods.txt](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13678034/ActiveMods.txt)
[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13678036/Engine.log)

Note that it does not result in a CTD but rather permanently breaks my save game, since relaunching skyrim does not fix the issue. The only solution I currently have is to start a new save and never use magic.

I hope this helps identify the root of the problem, as I would greatly like to use Pandora+.

**Comment by Monitor144hz** [comment]
Closing as this is a duplicate issue, but the info is appreciated. Please follow #12 for updates on this bug from now on.
