### ISSUE TITLE
Here is the Engline.log file

### ISSUE THREAD

**Issue by diriLeSh** [Monitor144hz/Pandora-Behaviour-Engine-Plus#30]
Hello Monitor,

First time i'm using Pandora BEP,  i run and i got a log file it's includes some "failed" lines..

How we can read this fails or warning ? I mean what it means and how we can solve this warnings ? or these are critical or not ?

Here is the log file:

WARN : Dispatcher > "Pandora Base" > defaultfemale~0_master > Remove > Element > #0755/triggers/Element0 > FAILED
WARN : Dispatcher > "HotKeySkill" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Dispatcher > "Kingsglaive for MCO" > defaultfemale~bashbehavior > Append > Element > eventNames > FAILED
WARN : Validator > defaultfemale~magicmountedbehavior > Duplicate Variable > iState_NPCSneaking > REMOVED
WARN : Dispatcher > "True Directional Movement - 360 Horse Archery" > defaultfemale~horsebehavior > Replace > Text > #0742/errorOutTranslation > FAILED
WARN : Validator > defaultfemale~mt_behavior > Duplicate Event > IdleFreaSorrowLoopEnter > REMOVED
WARN : Validator > defaultfemale~magicbehavior > Duplicate Event > PIE > REMOVED
WARN : Dispatcher > "Pandora Base" > defaultfemale~0_master > Remove > Element > #0755/triggers/Element3 > FAILED
WARN : Validator > defaultfemale~magicbehavior > Duplicate Variable > iState_NPCSneaking > REMOVED
WARN : Dispatcher > "Ice skating fixed for real" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Dispatcher > "Pandora Base" > defaultfemale~0_master > Remove > Element > #0768/triggers/Element0 > FAILED
WARN : Dispatcher > "Pandora Base" > defaultfemale~0_master > Remove > Element > #0768/triggers/Element2 > FAILED
WARN : Dispatcher > "SCAR" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > Collision_Start > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > PIE > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > MCO_EndAnimation > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > MCO_WinOpen > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > MCO_WinClose > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > MCO_PowerWinOpen > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > MCO_PowerWinClose > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > MCO_InputBuffer > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > PIE > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > Collision_Start > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > Collision_Add > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > Collision_Remove > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > Collision_ClearTargets > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > PIE > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > Collision_AttackEnd > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Variable > MCO_BlendLength > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Variable > MCO_IsInRecovery > REMOVED
WARN : Validator > defaultfemale~0_master > Duplicate Event > PIE > REMOVED
WARN : Validator > defaultfemale~0_master > Duplicate Event > CastStop > REMOVED
WARN : Validator > defaultfemale~0_master > Duplicate Event > Collision_Start > REMOVED
WARN : Validator > defaultfemale~0_master > Duplicate Event > Collision_Add > REMOVED
WARN : Validator > defaultfemale~0_master > Duplicate Event > Collision_Remove > REMOVED
WARN : Validator > defaultfemale~0_master > Duplicate Event > Collision_ClearTargets > REMOVED
WARN : Validator > defaultfemale~0_master > Duplicate Event > PIE > REMOVED
WARN : Validator > defaultfemale~0_master > Duplicate Event > Collision_Cancel > REMOVED
WARN : Validator > defaultfemale~0_master > Duplicate Event > OST_ExitAnim > REMOVED
WARN : Validator > defaultfemale~0_master > Duplicate Event > PIE > REMOVED
WARN : Validator > defaultfemale~0_master > Duplicate Event > PIE > REMOVED
INFO : Mod 1 : Attack - Distar Experience - v.1.0.0
INFO : Mod 2 : Maxsu Block Overhaul - v.1.0.0
INFO : Mod 3 : Precision - v.1.0.0
INFO : Mod 4 : Dodge - Distar Experience - v.1.0.0
INFO : Mod 5 : 360 Movement Behavior SE - v.1.0.0
INFO : Mod 6 : Dual Wield Block - v.1.0.0
INFO : Mod 7 : Payload Interpreter - v.1.0.0
INFO : Mod 8 : EVG Animated Traversal - v.1.0.0
INFO : Mod 9 : Gender Specific Animations - v.1.0.0
INFO : Mod 10 : HotKeySkill - v.1.0.0
INFO : Mod 11 : Ice skating fixed for real - v.1.0.0
INFO : Mod 12 : Animated Jump Attack - v.1.0.0
INFO : Mod 13 : Kingsglaive for MCO - v.1.0.0
INFO : Mod 14 : Nemesis Base - v.1.0.0
INFO : Mod 15 : OAnims - v.1.0.0
INFO : Mod 16 : OpenSex - v.1.0.0
INFO : Mod 17 : OStim - v.1.0.0
INFO : Mod 18 : Skyrim's Paraglider - v.1.0.0
INFO : Mod 19 : Retimed Hit Frame - v.1.0.0
INFO : Mod 20 : SCAR - v.1.0.0
INFO : Mod 21 : Sprint Bug Fix - v.1.0.0
INFO : Mod 22 : True Directional Movement - 360 Horse Archery - v.1.0.0
INFO : Mod 23 : True Directional Movement - Procedural Leaning - v.1.0.0
INFO : Mod 24 : True Directional Movement - Headtracking - v.1.0.0
INFO : Mod 25 : AnimatedShouts - v.1.0.0
INFO : Mod 26 : Animation Teleport Bug Fix - v.1.0.0
INFO : Mod 27 : FallingArtExpan - v.1.0.0
INFO : Mod 28 : Pandora Base - v.1.0.0

**Comment by Monitor144hz** [comment]
Warnings are not an issue most of the time, unless you experience a problem in gameplay. Also I see some warnings for Pandora Base that shouldn't be there unless you are on older versions, so please make sure to update to the latest version. See the [readme](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus#verbose-logging) on the main page for more information
