### ISSUE TITLE
Does not work with GsPoses

### ISSUE THREAD

**Issue by SerkelDays** [Monitor144hz/Pandora-Behaviour-Engine-Plus#31]
When running an animation with the mod mentioned above, it does not show any animation, when checking the animation log you cannot even see that the hkx load as if they were not there, can you please check that?

**Comment by SerkelDays** [comment]
Here a preview: https://streamable.com/fp425r

**Comment by Monitor144hz** [comment]
[GSPoses Pandora Patch.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13733064/GSPoses.Pandora.Patch.zip)

not a bug, FNIS mods need porting. Use this patch @SerkelDays
