### ISSUE TITLE
Discussions section

### ISSUE THREAD

**Issue by elbadcode** [Monitor144hz/Pandora-Behaviour-Engine-Plus#33]
Hey since the tool is quite far along now and seems to be getting more attention could you open a discussions section on here so users can ask less pressing questions and help each other out to identify incompatibilities between mods or share patches we've made for FNIS mods, etc. Just thought that might be helpful for those of us using the program and to hopefully reduce the amount of pings you get for known issues or casual questions and to give feedback on new releases.

**Comment by Monitor144hz** [comment]
Enabled discussions.
