### ISSUE TITLE
MME mod Problems

### ISSUE THREAD

**Issue by Kyationa** [Monitor144hz/Pandora-Behaviour-Engine-Plus#46]
Milk Mod Economy seems to have problems working with Pandora engine the interaction with the milking machine does not activated the script and animation conversion of mod seems to work no errors at all just seems like script enter for it to work when activate seems to try and fail instantly everything else works.

**Comment by Monitor144hz** [comment]
send me the pandora patch that you generated @Kyationa

**Comment by Kyationa** [comment]
[pandora MME patch.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13799926/pandora.MME.patch.zip)
these are the patch files i have for it.

**Comment by Kyationa** [comment]
would it be better if i sent you all the patch files that I made for the mods I use?

**Comment by Monitor144hz** [comment]
wrong folder structure, see wiki

```└───Pandora_Engine
    └───mod
        └───flufyfx
            │   info.ini
            │
            ├───0_master
            │   └───inject
            │       └───#0340
            │               FNIS_FlufyPose_Behavior.xml
            │
            ├───defaultfemale
            │   └───inject
            │           FNIS_FlufyPose_Behavior.xml
            │
            └───defaultmale
                └───inject
                        FNIS_FlufyPose_Behavior.xml
                        ```
 ```
 C:.
│   FNIS_MME_Behavior.hkx
│   FNIS_MME_Behavior.xml
│
└───MME
    │   info.ini
    │
    ├───defaultfemale~0_master
    │   └───inject
    │       └───#0340
    │               FNIS_MME_Behavior.xml
    │
    ├───defaultfemale~defaultfemale
    │   └───inject
    │           FNIS_MME_Behavior.xml
    │
    └───defaultmale~defaultmale
        └───inject
                FNIS_MME_Behavior.xml
                ```
  wrong. Where did the Pandora_Engine folder go?

**Comment by Kyationa** [comment]
so i don't need any of the files outside of the Pandora folder with the changes in the name if i understand correctly

**Comment by Kyationa** [comment]
is there a example mod for animal animations so i can figure that out?

**Comment by Monitor144hz** [comment]
@Kyationa next major version should have automatic FNIS compatibility, but example patches are on the [modding guild website.](https://modding-guild.com/mod/pandora-behaviour-engine-patch-hub/)

**Comment by Kyationa** [comment]
thanks for info
