### ISSUE TITLE
AMCO + Jumping Attack export error

### ISSUE THREAD

**Issue by DJ4ddi** [Monitor144hz/Pandora-Behaviour-Engine-Plus#47]
### Summary
When using the (Nemesis compatible) mod **Attack - MCO|DXP** ([source](https://modding-guild.com/mod/attack-mcodxp/)) with **Jumping Attack** ([source](https://www.nexusmods.com/skyrimspecialedition/mods/68043)), Pandora shows a fatal export error (and does not generate correct outputs).

### Reproduction
- Install AMCO (and optionally its dependencies, although not needed to reproduce the issue).
- Install Jumping Attack with the AMCO patch (included in FoMod).
- Run Pandora with AMCO enabled.

### Details
Versions installed:
- Pandora 0.8.7-alpha
- Attack - MCO|DXP 1.6.0.6
- Jumping Attack 1.31
- Open Animation Replacer 2.0.2
- Animation Motion Revolution 1.5.3
- Payload Interpreter 1.0.1
- MCO Universal Support 1.0

Engine.log output:
```
FATAL : Export > defaultfemale~1hm_behavior > FAILED > Could not convert 'HKX2.hkbStateMachineTransitionInfoArray' to 'HKX2.hkbExpressionCondition'. Is source malformed?
INFO : Mod 1 : Pandora Base - v.1.0.0
INFO : Mod 2 : Attack - Modern Combat Overhaul - v.1.0.0
```

Using the same setup in Nemesis works without issues.

**Comment by Monitor144hz** [comment]
Not reproducible on my end with either versions of MCO ADXP. sounds like malformed template files. Redownload, reinstall, and retest please.

If anyone else has experienced similar issue speak now or forever hold your peace

**Comment by elbadcode** [comment]
I've had the same issue several times across several versions and have always been able to resolve. I don't think its actually MCO itself but rather a conflicting mod. I can't remember off the top of my head which mod it was but I'd suggest reinstalling/regenerating any patches and try removing stuff until it works. Also be sure to remove any leftover nemesis or pandora patches, e.g. in mo2 overwrite folder

**Comment by elbadcode** [comment]
Jumping attack is not the issue. Here is my engine log for a working set of mods. ABR and mco required some ESP edits and OAR shenanigans to actually be usable but no edits to the nemesis patches and all latest versions.

[engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13802092/engine.log)

**Comment by elbadcode** [comment]
Jump attack is the last behavior mod in my load order as that is the correct way to use it with its compatibility patches

**Comment by Monitor144hz** [comment]
@DJ4ddi Jumping Attack has multiple optional patches in the fomod, are you sure you didn't install any for mods that weren't active?

**Comment by Monitor144hz** [comment]
nvm, reproducable. investigating now

**Comment by Monitor144hz** [comment]
@DJ4ddi Delete `#amco$10.txt` and put this in file in its place
[#amco$8.txt](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13805856/amco.8.txt)

After MCO updated and changed its patch files, Jumping Attack patch was left overwriting the wrong node and this caused an error. Strictly speaking, not a Pandora issue but the solution is here anyway.

**Comment by elbadcode** [comment]
I'm a bit confused how I've been able to patch it then as I had the #amc$10 override along with newest MCO version and it worked in game. I realized I had an old pandora output active. After clearing out old outputs and generating to a fresh folder without this fix it failed to generate 1hm_behavior although engine.log still didn't contain the error message. After the fix it does generate that file to a fresh folder and works in game. It seems that having the missing 1hm_behavior file in the old output actually allowed the patch to work as reenabling that output and undoing the fix again produces a working output and actually writes to both folders. Copying just the missing 1hm_behavior into a fresh output also works. Is this intended behavior? Honestly seems kind of useful to be able to use a fallback behavior file.

**Comment by Monitor144hz** [comment]
Intended behavior yes, it's up to the user to handle the output. Pandora only handles behavior files that are edited. if 1hm_behavior wasn't patched by any mods or failed to patch, then it won't produce that single file. Partial failure should still leave users with a (mostly intact) setup.
