### ISSUE TITLE
FNIS Questions

### ISSUE THREAD

**Issue by DarklyNightly** [Monitor144hz/Pandora-Behaviour-Engine-Plus#49]
Do i disable fnis?
Does it generate fnis dummy plugin?

**Comment by Monitor144hz** [comment]
1. Disable FNIS but can keep FNIS mods enabled
2. No, use FNIS.esp from [XPMSE patch here ](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/releases/tag/v0.6.9-alpha)

3. Use Discussions next time for questions tab, Issues is for reporting bugs and feature requests

**Comment by DarklyNightly** [comment]
sorry but how do i use the patch?
