### ISSUE TITLE
joy of perspective gets messed up 

### ISSUE THREAD

**Issue by DarklyNightly** [Monitor144hz/Pandora-Behaviour-Engine-Plus#51]
when i deleted this file after running pandora, joy of perspective messed up in first person mode
![Screenshot 2024-01-01 170728](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/75499681/a49b5bfd-a3e5-4397-a7c4-c139c437b9b4)
![Screenshot 2024-01-01 170736](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/75499681/05a5491f-1c81-4bb3-8a5d-4e285dce8b9f)

**Comment by DarklyNightly** [comment]
the first person meshes

**Comment by Monitor144hz** [comment]
joy of perspective is outdated and obsolete, use Improved Camera SE
