### ISSUE TITLE
Animation issues

### ISSUE THREAD

**Issue by Kyationa** [Monitor144hz/Pandora-Behaviour-Engine-Plus#52]
i tried a lot of different things magic don't work at all keeps me in place or it even just glides the character around don't know what causes it. open animation replacer only loads if FNIS is loaded with Pandora and power attacks seems to not work properly either don't know what causes this at all everything loads in Pandora.

**Comment by Monitor144hz** [comment]
Not enough information. What am I supposed to use to reproduce the issue? Where is your engine.log? Your output zipped?

**Comment by Kyationa** [comment]
sorry i forgot the engine.log file this is the output folder.
[Pandora.Behaviour.Engine.v0.9.1-alpha.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13813083/Pandora.Behaviour.Engine.v0.9.1-alpha.zip)

**Comment by Kyationa** [comment]
also one of my friends had the issue with magic and his was fixed by removing jump attack so it seems different mods might effect how it generates the magic behavior I will go through my mod list and find all the mods that add to magic casting/ magic behavior. it might help i could also post my mod list if that could help.

**Comment by Monitor144hz** [comment]
Fixed with #62 . Update engine to v1.0.0-alpha @Kyationa, and thanks for reporting. Let me know if issue persists.
