### ISSUE TITLE
Human Vampire Lord Issues

### ISSUE THREAD

**Issue by DarklyNightly** [Monitor144hz/Pandora-Behaviour-Engine-Plus#53]
I use these 3 mods, when i transform into a vampire lord i get flipped upside down and clip though the floor 
https://www.nexusmods.com/skyrimspecialedition/mods/66696 
https://www.nexusmods.com/skyrimspecialedition/mods/67062
https://www.nexusmods.com/skyrimspecialedition/mods/87166

**Comment by DarklyNightly** [comment]
![489830_20240101234412_1](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/75499681/e9a69f05-8173-4ece-a54d-9291be3675e0)

**Comment by DarklyNightly** [comment]
i have narrowed it down to Humanoid Vampire lord Bats power fix and Gender specific animations (DAR) https://www.nexusmods.com/skyrimspecialedition/mods/67062?tab=posts
![Screenshot 2024-01-01 234951](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/75499681/22dbb406-c4ff-401a-91de-fcdbd6eecad4)

**Comment by DarklyNightly** [comment]
its asks to delete the file but i chose to restore it

**Comment by DarklyNightly** [comment]
animations work if i dont delete the skeleton 
![489830_20240101235453_1](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/75499681/60116b8f-4aab-499f-b6f2-c6ac51c83ec7)

**Comment by Monitor144hz** [comment]
Output conflict resolution is the responsibility of the user, not the program. The engine itself cannot interact with the mod manager.
