### ISSUE TITLE
SexLab Creatures that don't animate (wolf + draugr + hagraven + chaurus)

### ISSUE THREAD

**Issue by TheMud** [Monitor144hz/Pandora-Behaviour-Engine-Plus#57]
SL Creatures support works for most creatures as of the current release, except for wolves, draugr, and hagravens - they don't animate in SL but appear to be functioning entities otherwise (they're not T-posing, at least).

Wolves apparently aren't generating a behavior file so that might be the problem?

Draugr and hagravens do generate the necessary files, and Precision Creatures works with draugr, so they seem to be missing some SL-specific data?

**Comment by Monitor144hz** [comment]
Confirmed, thanks for reporting. Looking into the issue

**Comment by PinyaGit** [comment]
Found similar problems with myself. Checked through Hentai Creatures and surprisingly all creatures worked except draugr. Unfortunately, I didn't check wolves. For now, I'm generating the old fashioned way, first FNIS then Nemesis, disabling the Output folders between them

**Comment by Monitor144hz** [comment]
Found the cause, should be fixed in the next version

**Comment by PinyaGit** [comment]
Good evening. Checked the latest version of Pandora. Animations now work correctly. Check for yourself.

**Comment by Monitor144hz** [comment]
Yep, reported similar results. Problem seems to be fixed.
