### ISSUE TITLE
Humanoid Vampire lord Bats power fix and Gender specific animations (DAR)

### ISSUE THREAD

**Issue by DarklyNightly** [Monitor144hz/Pandora-Behaviour-Engine-Plus#59]
I removed all vampire animations mods and after running pandora it asks to delete the skeleton in character assets which breaks the vampire lord form

**Comment by Monitor144hz** [comment]
That sounds like a Vortex mod manager issue. I appreciate the report but this isn't something I can fix. If you were using MO2 I'd simply say let the engine output win all conflicts but I have no idea why Vortex is deleting files nor can I do anything about it from the engine.

**Comment by DarklyNightly** [comment]
i will switch to MO2 and see if the issue still persists
