### ISSUE TITLE
Skeleton Hkx From External Mods Gets Deleted by Pandora

### ISSUE THREAD

**Issue by DarklyNightly** [Monitor144hz/Pandora-Behaviour-Engine-Plus#60]
**dont close this until we have figured it out**

Steps to reproduce:
1. Run pandora as a tool in vortex
2. Deploy after launch has finished 
3. Vortex tells you that files have been changed externally and if you want to delete the file or revert it

issue happens when pandora generates the fallowing:
47 animations added to atronachflame.
25 animations added to atronachfrostproject.
35 animations added to atronachstormproject.
51 animations added to bearproject.
1354 animations added to dogproject.
1354 animations added to wolfproject.
15271 animations added to defaultfemale.
15271 animations added to defaultmale.
138 animations added to chaurusproject.
4 animations added to highlandcowproject.
24 animations added to deerproject.
72 animations added to chaurusflyer.
71 animations added to vampirebruteproject.
61 animations added to benthiclurkerproject.
62 animations added to boarproject.
10 animations added to ballistacenturion.
44 animations added to hmdaedra.
11 animations added to netchproject.
392 animations added to rieklingproject.
66 animations added to scribproject.
38 animations added to dragonproject.
24 animations added to dragon_priest.
251 animations added to draugrproject.
251 animations added to draugrskeletonproject.
30 animations added to spherecenturion.
31 animations added to dwarvenspidercenturionproject.
22 animations added to steamproject.
249 animations added to falmerproject.
118 animations added to frostbitespiderproject.
99 animations added to giantproject.
19 animations added to goatproject.
8 animations added to hagravenproject.
24 animations added to horkerproject.
188 animations added to horseproject.
10 animations added to icewraithproject.
19 animations added to mammothproject.
39 animations added to sabrecatproject.
141 animations added to skeeverproject.
20 animations added to slaughterfishproject.
67 animations added to spriggan.
181 animations added to trollproject.
32 animations added to vampirelord.
226 animations added to werewolfbeastproject.
4 animations added to wispproject.
4 animations added to chickenproject.
24 animations added to hareproject.

**Comment by DarklyNightly** [comment]
![Screenshot 2024-01-02 144140](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/75499681/aa7588fd-2b9a-4607-ad84-aecb57ef84fb)
![Screenshot 2024-01-02 144156](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/75499681/510945d0-1daa-4e6e-a654-1715a61ca3ed)
![Screenshot 2024-01-02 144210](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/75499681/2f7587a9-19f5-4cda-82cb-0adaaf8dbeb9)
![Screenshot 2024-01-02 144223](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/75499681/35c9a83f-b224-4c8d-85de-42aff122dd9b)
![Screenshot 2024-01-02 144236](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/75499681/3b4bdb38-0e50-4b45-9d47-8a24afd41630)

**Comment by DarklyNightly** [comment]
so from what i figured out when pandora adds the animations to the beasts it also changes the meshes in character assests and not just the animations?

**Comment by DarklyNightly** [comment]
the mods that are affected are creature animation mods, i guess vampire lord is also a creature, which explains the issues i have been having with #59 and #53

**Comment by Monitor144hz** [comment]
> so from what i figured out when pandora adds the animations to the beasts it also changes the meshes in character assests and not just the animations?

The only thing it does related to that is delete any loose behavior files, because all the vanilla behaviors are in bsas, therefore it assumes anything outside of that is old engine output. 

If you are using some kind of skeleton replacer than keep it disabled, run Pandora, then reenable it.

**Comment by Monitor144hz** [comment]
@DarklyNightly just choose the option to revert or not save change in Vortex

**Comment by Monitor144hz** [comment]
@DarklyNightly update to v1.0.0-alpha

**Comment by DarklyNightly** [comment]
> @DarklyNightly update to v1.0.0-alpha

thanks soo much i will try it right away
