### ISSUE TITLE
Ctd with the new Pandora update

### ISSUE THREAD

**Issue by SerkelDays** [Monitor144hz/Pandora-Behaviour-Engine-Plus#61]
When updating to 0.9.1, and running the Pandora exe again, when loading a saved game, a ctd occurs, and seeing the crash log, it has something to do with FNIS meshes, could you please check it?

[crash-2024-01-02-20-55-29.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13813894/crash-2024-01-02-20-55-29.log)

**Comment by Monitor144hz** [comment]
@SerkelDays Please zip up your Pandora Output and send it to me

**Comment by SerkelDays** [comment]
Nvm, in a new game it is fixed, but I still get a little confused
