### ISSUE TITLE
No animations with Animated Whistling mod

### ISSUE THREAD

**Issue by urbonx** [Monitor144hz/Pandora-Behaviour-Engine-Plus#67]
Isn't working with this mod: [https://www.nexusmods.com/skyrimspecialedition/mods/76733?tab=files](url)
No animations.

Also, some warnings in the log related to other mods btw.
[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13823284/Engine.log)

**Comment by Monitor144hz** [comment]
See #76
