### ISSUE TITLE
Main Menu CTD with pandora v1.00a enabled

### ISSUE THREAD

**Issue by imanoobyasu0** [Monitor144hz/Pandora-Behaviour-Engine-Plus#70]
[crash-2024-01-07-08-00-37.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13852646/crash-2024-01-07-08-00-37.log)

Wasnt updating pandora version so didnt have any leftover output that I know of. Using XPMSSE Light. CTD when game is loading at main menu, just before Open Animation Replacer is supposed to load animations at the top right.

**Comment by imanoobyasu0** [comment]
Nvm the issue was with xing noArt behavior. Disabled the patch for that in Pandora and it worked fine afterwards.

**Comment by imanoobyasu0** [comment]
Nvm the issue was with xing noArt behavior. Disabled the patch for that in Pandora and it worked fine afterwards.

**Comment by Monitor144hz** [comment]
What version were you on @imanoobyasu0? That issue has solved in latest version. Unlike stable release, alpha release means you must be on latest version to report any bugs

**Comment by imanoobyasu0** [comment]
Version of Pandora? or xing noArt behavior. If its pandora, I'm on v1.0.0 alpha
