### ISSUE TITLE
Q re README.md for MO2 users

### ISSUE THREAD

**Issue by SteveTownsend** [Monitor144hz/Pandora-Behaviour-Engine-Plus#72]
I am an existing Nemesis user. What do I do about Nemesis?
Obviously I need to disable my _Nemesis Output_ mod. Other than that, is Pandora a drop-in replacement, or do I still need Nemesis for the behaviour patches it includes?
Sorry if this is the wrong forum, if there is a Discord please lmk.

**Comment by elbadcode** [comment]
It's drop in. I personally go into my nemesis folder and delete the unneeded default mods and leave the nemesis application enabled in mo2 but disable the output. You may not even need to disable your output tbh but it is good practice to do so anyway

**Comment by Monitor144hz** [comment]
Disable Nemesis Engine and Output. You can reach me in the Modding Guild public server.

**Comment by SteveTownsend** [comment]
thanks
