### ISSUE TITLE
Nemesis PCEA does not working

### ISSUE THREAD

**Issue by Scordem** [Monitor144hz/Pandora-Behaviour-Engine-Plus#73]
Project New Reign - Nemesis PCEA
[https://www.nexusmods.com/skyrimspecialedition/mods/31667](https://www.nexusmods.com/skyrimspecialedition/mods/31667)

Running Pandora does not seem to work as the logs(Engine.log) do not include the results.

**Comment by elbadcode** [comment]
Why would you even need this? Just use OAR

**Comment by Monitor144hz** [comment]
Unfortunately there's a point here. Nemesis PCEA is not supported.
