### ISSUE TITLE
animations don`t work

### ISSUE THREAD

**Issue by Joeyleeyp** [Monitor144hz/Pandora-Behaviour-Engine-Plus#74]
I have some animations like Craft Alchemy animation,Craft Enchanting animation.
their path: Meshes\actors\character\animations\female
they don`t work :(

**Comment by Kyationa** [comment]
> I have some animations like Craft Alchemy animation,Craft Enchanting animation. their path: Meshes\actors\character\animations\female they don`t work :(

hey in order for any help you would want to zip up your output folder for Pandora and post it in here also what mods exactly there are a few the animated the alchemy and enchanting so if you wanna post a link to them that would also help

**Comment by Monitor144hz** [comment]
Closed for lack of information
