### ISSUE TITLE
Pandora seems not respect the output config in MO2

### ISSUE THREAD

**Issue by weizhen199** [Monitor144hz/Pandora-Behaviour-Engine-Plus#75]
Pandora seems not respect the output config in MO2, and always output in Overwite folder.

**Comment by Fuzzlesz** [comment]
Works fine for me

**Comment by Kyationa** [comment]
> Pandora seems not respect the output config in MO2, and always output in Overwite folder.

it happens delete your output folder make a new one and change it to that one and delete all of the files it put in the overwrite folder of mo2 then try again it is a mo2 problem not a Pandora problem

**Comment by weizhen199** [comment]
it happens 
1. delete your output folder
2. make a new one and change it to that one
3. delete all of the files it put in the overwrite folder of mo2 (I can't understand this)
4. try again

**Comment by weizhen199** [comment]
> it happens
> 
> 1. delete your output folder
> 2. make a new one and change it to that one
> 3. delete all of the files it put in the overwrite folder of mo2 (I can't understand this)
> 4. try again



> > Pandora seems not respect the output config in MO2, and always output in Overwite folder.
> 
> it happens delete your output folder make a new one and change it to that one and delete all of the files it put in the overwrite folder of mo2 then try again it is a mo2 problem not a Pandora problem

it happens

delete your output folder
make a new one and change it to that one
delete all of the files it put in the overwrite folder of mo2 (I can't understand this)
try again

**Comment by weizhen199** [comment]
> > Pandora seems not respect the output config in MO2, and always output in Overwite folder.
> 
> it happens delete your output folder make a new one and change it to that one and delete all of the files it put in the overwrite folder of mo2 then try again it is a mo2 problem not a Pandora problem

it happens

delete your output folder
make a new one and change it to that one
delete all of the files it put in the overwrite folder of mo2 (I can't understand this)
try again
