### ISSUE TITLE
Trolls attack only once.

### ISSUE THREAD

**Issue by MaskPlague** [Monitor144hz/Pandora-Behaviour-Engine-Plus#78]
Trolls will roar and attack once and will not attack again. They just circle around any character they are in combat with.
Engine.log: [Pastebin](https://pastebin.com/hgxaR0Y4)

**Comment by Monitor144hz** [comment]
confirmed, thanks for report

**Comment by Monitor144hz** [comment]
Cause found. Fix in next version

**Comment by DJLegends1011** [comment]
> Cause found. Fix in next version

sweet found out that trolls t-pose with pandora

**Comment by MaskPlague** [comment]
> Cause found. Fix in next version

Yay. Waiting patiently.

**Comment by Monitor144hz** [comment]
Should be fixed in latest version.

**Comment by MaskPlague** [comment]
> Should be fixed in latest version.

Unfortunately, it still isn't fixed for me.
