### ISSUE TITLE
ver 1.13 combat animations completely doesnt work

### ISSUE THREAD

**Issue by imanoobyasu0** [Monitor144hz/Pandora-Behaviour-Engine-Plus#91]
For unique weapons, the character just t-poses while for existing weapon types, it just reverts to default vanilla animations. Think mods like paraglider and all that doesnt work as well, didnt test any sexlab or ostim mods so not sure if those works.

**Comment by Irich3022** [comment]
Nemesis modes that worked in 1.1 don't work anymore.
And it seems like all of the combat animations have reverted to vanilla animations.

**Comment by SchaiRand** [comment]
There's quite a few issues with 1.13 right now, but it seems to boil down to mods relying on Nemesis patch (MCO, Immersive Interactions,...) not working after patching.
