### ISSUE TITLE
TK Dodge rolls on the spot.

### ISSUE THREAD

**Issue by LucaciuSAlex** [Monitor144hz/Pandora-Behaviour-Engine-Plus#95]
When using TK Dodge RE with Pandora, the character rolls/steps on the spot, it does not move towards the dodge direction. This does not happen while running Nemesis.

**Comment by Monitor144hz** [comment]
See #28. It's an issue with how TK Dodge is built and how it conflicts with one of Pandora's design decision. Unless TK Dodge gets some AMR support or the engine adds an alternative way for motion data, this will persist.
