### ISSUE TITLE
Trolls still don't attack again.

### ISSUE THREAD

**Issue by MaskPlague** [Monitor144hz/Pandora-Behaviour-Engine-Plus#96]
Using 1.1.4 the issue with trolls is still not resolved. Having any animation/behaviors for trolls (tested with LL's SL) will cause "WARN : Validator > trollproject~trollbehavior > Duplicate Event > SoundPlay.NPCTrollAttackB > REMOVED" to appear in the engine.log and trolls will no longer attack a second time. (I haven't tested distar's Creatures : Troll – MCO|DXP as I'm not signed up for his Patreon.)

On 1.6.640
my regular set up; engine.log: https://pastebin.com/2FXYYdgX
just SL with no other mods except its requirements; engine.log: https://pastebin.com/EyFQ9yZ6

**Comment by Monitor144hz** [comment]
check tag v1.1.5-alpha. close this issue if that fixes the problem @MaskPlague .

**Comment by MaskPlague** [comment]
That fixed it, greatly appreciated.
