### ISSUE TITLE
pandora1.1.5 still can't block while moving

### ISSUE THREAD

**Issue by AntimonyF5** [Monitor144hz/Pandora-Behaviour-Engine-Plus#99]
And when I move while blocking, the blocking animation will be stoped
This problem already existed in version 1.1.0

**Comment by Monitor144hz** [comment]
Are you using the latest XPMSE universal patch? @AntimonyF5

**Comment by AntimonyF5** [comment]
> 您使用的是最新的 XPMSE 通用补丁吗？@AntimonyF5

Is it in the 1.1.3 release?

**Comment by AntimonyF5** [comment]
> Are you using the latest XPMSE universal patch? @AntimonyF5

I apologize for ignoring patches from past versions. But I'd also suggest adding these key patch downloads to the latest version as well

**Comment by Monitor144hz** [comment]
I will consider adding the patch to the base engine.
